const test=require('node:test'),assert=require('node:assert/strict');const {Duplex}=require('node:stream');const {IapLink,Accessory,marker,packet,csm,param,fields,u16,u32,identification}=require('../build/engine/iap');const {NowPlaying}=require('../build/engine/nowPlaying');
function harness(){const writes=[],stream=new Duplex({read(){},write(b,e,cb){writes.push(Buffer.from(b));cb()}}),link=new IapLink(stream);link.feed(marker);link.feed(packet(128,50,99,0,Buffer.from([1,30,255,255,15,160,1,244,4,3,10,0,1,12,1,2])));link.feed(packet(64,50,99,0));return {link,writes}}
test('iAP2 stream fragments, duplicate and out-of-order packets deliver one ordered CSM message',()=>{const {link}=harness(),received=[];link.on('csm',(id)=>received.push(id));const message=csm(0x1d00),a=packet(64,51,99,10,message.subarray(0,3)),b=packet(64,52,99,10,message.subarray(3));link.feed(b);link.feed(a.subarray(0,7));link.feed(a.subarray(7));link.feed(a);assert.deepEqual(received,[0x1d00]);link.close()});
test('iAP2 checksum corruption does not deliver a control message',()=>{const {link}=harness(),received=[];link.on('csm',id=>received.push(id));const msg=packet(64,51,99,10,csm(0x1d00));msg[msg.length-1]^=1;link.feed(msg);assert.deepEqual(received,[]);link.close()});
test('Wi-Fi tunnel initiates a new version-2 zero-ACK link and permits subscription burst',()=>{const writes=[],stream=new Duplex({read(){},write(b,e,cb){writes.push(Buffer.from(b));cb()}}),link=new IapLink(stream,{initiate:true,zeroAck:true});assert(writes[0].equals(marker));assert.equal(writes[1][4],128);assert.equal(writes[1][21],2);link.feed(packet(128,40,99,0,Buffer.from([1,4,255,255,0,0,0,0,0,0,10,0,2,12,1,2])));link.feed(packet(64,40,99,0));for(let i=0;i<12;i++)link.send(csm(0x5000));assert.equal(writes.filter(b=>b.length>15&&b[7]===10).length,12);link.close()});
test('wireless identification advertises authentication messages from Android source',()=>{const b=identification({serial:'PUBLIC-TEST',btMac:'02:00:00:00:00:01',ssid:'TEST-NETWORK'}),p=fields(b.subarray(6));assert(p.has(17)&&p.has(24)&&!p.has(16));assert(p.get(6).includes(Buffer.from('aa01','hex')));assert(!p.get(6).includes(Buffer.from('a101','hex')))});
test('wireless handoff is withheld until authentication; transport notification resends Wi-Fi',async()=>{const {link,writes}=harness(),a=new Accessory(link,{certificate:async()=>Buffer.from([1,2]),sign:async()=>Buffer.alloc(64),protocolMajor:async()=>3},{ssid:'TEST-NETWORK',password:'public-test-only',channel:6,btMac:'02:00:00:00:00:01',apMac:'02:00:00:00:00:02',host:'fe80::1',port:17000,pk:'public-test',serial:'TEST'});let seq=50;const feed=(id,p=[])=>link.feed(packet(64,++seq,99,10,csm(id,p)));let started=0;a.on('negotiation',()=>started++);feed(0x4300);assert.equal(started,0);feed(0x1d02);feed(0xaa05);await new Promise(r=>setImmediate(r));feed(0x5702);feed(0x4e0e);feed(0x4300);await new Promise(r=>setImmediate(r));assert.equal(started,1);assert.equal(writes.filter(b=>b.length>15&&b.readUInt16BE(13)===0x5703).length,2);a.close()});
const png=Buffer.from('89504e470d0a1a0a00000000','hex');function track(id,title,ftid){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(id));return new Map([[0,Buffer.concat([param(0,b),param(1,Buffer.from(title+'\0')),param(4,u32(120000)),...ftid!==undefined?[param(26,Buffer.from([ftid]))]:[]])],[1,Buffer.concat([param(0,Buffer.from([1])),param(1,u32(1000)),param(13)])]])}
test('lyrics title updates preserve cover; confirmed track change clears and stale artwork is rejected',()=>{const updates=[],n=new NowPlaying((state,changed)=>updates.push({state,changed}),()=>{});n.apply(track(1,'Song',7));n.file(Buffer.concat([Buffer.from([7,192]),png]));assert(n.state.artwork.equals(png));n.apply(new Map([[0,param(1,Buffer.from('歌词一行\0'))]]));assert.equal(n.state.title,'歌词一行');assert(n.state.artwork.equals(png));assert.equal(updates.at(-1).changed,false);n.file(Buffer.from([7,4]));n.file(Buffer.concat([Buffer.from([7,128]),png]));n.apply(track(2,'Next',8));assert.equal(n.state.artwork,undefined);n.file(Buffer.from([7,64]));assert.equal(n.state.artwork,undefined);n.file(Buffer.concat([Buffer.from([8,192]),png]));assert(n.state.artwork.equals(png))});
test('seek requires capability and duration, and optimistic seek ignores old progress briefly',()=>{const n=new NowPlaying(()=>{},()=>{});assert.equal(n.seek(1000),false);n.apply(track(1,'Song'));assert.equal(n.seek(42000),true);n.apply(new Map([[1,param(1,u32(2000))]]));assert(n.state.positionMs>=42000);n.apply(new Map([[1,param(1,u32(42500))]]));assert.equal(n.state.positionMs,42500)});

test('lyrics remain live while unchanged artwork never crosses IPC again',()=>{const updates=[],n=new NowPlaying((state,changed)=>updates.push({state,changed}),()=>{});n.apply(track(1,'Song',7));n.file(Buffer.concat([Buffer.from([7,192]),png]));assert(updates.at(-1).state.artwork.equals(png));const before=updates.length;for(let i=0;i<200;i++)n.apply(new Map([[0,Buffer.concat([param(1,Buffer.from('line'+i)),param(6,Buffer.from('album'+i))])]]));assert.equal(updates.length,before+200);assert(updates.slice(before).every(u=>!u.changed&&!u.state.artwork));n.file(Buffer.concat([Buffer.from([7,192]),png]));assert.equal(updates.length,before+200);assert(n.state.artwork.equals(png));n.close()});
test('changing covers are coalesced independently of lyrics and track changes bypass cooldown',async()=>{const updates=[],n=new NowPlaying((state,changed)=>updates.push({state,changed}),()=>{});n.apply(track(1,'Song',7));n.file(Buffer.concat([Buffer.from([7,192]),png]));const before=updates.length;for(let i=0;i<100;i++){n.file(Buffer.concat([Buffer.from([7,192]),png,Buffer.from([i])]));n.apply(new Map([[0,param(1,Buffer.from('lyric'+i))]]))}assert.equal(updates.length,before+100);assert(updates.slice(before).every(u=>!u.changed&&!u.state.artwork));await new Promise(r=>setTimeout(r,5100));assert.equal(updates.length,before+101);assert.equal(updates.at(-1).state.artwork.at(-1),99);n.apply(track(2,'Next',8));assert.equal(updates.at(-1).changed,true);assert.equal(updates.at(-1).state.artwork,undefined);n.file(Buffer.concat([Buffer.from([8,192]),png]));assert(updates.at(-1).state.artwork.equals(png));n.file(Buffer.concat([Buffer.from([8,192]),png,Buffer.from([5])]));const count=updates.length;n.close();await new Promise(r=>setTimeout(r,50));assert.equal(updates.length,count)});
test('confirmed track and play state changes remain immediate',()=>{const updates=[],n=new NowPlaying((state,changed)=>updates.push({state,changed}),()=>{});n.apply(track(1,'Song'));n.apply(new Map([[0,param(1,Buffer.from('lyric'))]]));n.apply(track(2,'Next'));assert.equal(updates.at(-1).state.title,'Next');assert.equal(updates.at(-1).changed,true);n.apply(new Map([[1,param(0,Buffer.from([0]))]]));assert.equal(updates.at(-1).state.playing,false);n.close()});
