const $=id=>document.getElementById(id);let config,running=false,toastTimer,artUrl='',playing={};const logs=[];let displayItems=[],resolutionChoice;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
async function call(op,arg){const result=await winplay.call(op,arg);if(!result.ok)toast(result.error);return result}
function theme(dark){document.body.classList.toggle('dark',dark)}
function fieldKey(key){return config.wirelessMode==='lan'?({ssid:'lanSsid',password:'lanPassword',channel:'lanChannel',networkInterface:'lanNetworkInterface'}[key]||key):key}
function wirelessFields(){const lan=config.wirelessMode==='lan';$('wirelessMode').value=config.wirelessMode||'hotspot';$('wireless-help').textContent=lan?'Windows与iPhone 加入同一Wi-Fi，完成系统蓝牙配对。填写该路由器的共享密码和实际信道；客户端隔离、访客网络或企业认证可能阻止连接。':'由本机Windows 创建移动热点，让iPhone接入，并完成系统蓝牙配对。在系统设置中开启和配置热点后，填写相同信息。';$('hotspot-settings').textContent=lan?'打开定位设置':'打开移动热点';$('lan-bssid').hidden=!lan;$('ssid-label').textContent=lan?'局域网 Wi-Fi名称（SSID）':'本机热点名称';$('password-label').textContent=lan?'局域网 Wi-Fi共享密码':'本机热点密码';$('read-password').disabled=!config[fieldKey('ssid')];$('read-network').disabled=!lan;$('ssid').placeholder=lan?'两端共用的 Wi-Fi名称':'Windows移动热点名称';$('network-help').textContent=lan?'选择连接现有Wi-Fi的网卡；两端须可互访，允许Bonjour多播。':'选择Windows移动热点虚拟接口。';for(const key of ['ssid','password','channel'])$(key).value=config[fieldKey(key)];$('lanAccessPointMac').value=config.lanAccessPointMac}
function state(active){running=active;$('running-actions').hidden=!active;$('show-video').disabled=!active;$('start').textContent=active?'应用并重新连接':'启动接收';if(!active)$('fps-fallback').hidden=true;$('side-status').textContent=active?'接收中':'未连接';$('side-dot').classList.toggle('connected',active)}
function selected(select,items,value,empty){select.replaceChildren();if(empty){const option=document.createElement('option');option.value='';option.textContent=empty;select.append(option)}for(const item of items){const option=document.createElement('option');option.value=String(item.value);option.textContent=item.label;select.append(option)}if(!items.some(i=>String(i.value)===String(value))&&value!==''&&value!==0){const option=document.createElement('option');option.value=String(value);option.textContent='已保存设备（暂未检测到）';select.append(option)}select.value=String(value)}
let networkRequest=0;
async function networks(){const request=++networkRequest,mode=config.wirelessMode,key=fieldKey('networkInterface');const r=await call('networks');if(!r.ok||request!==networkRequest||mode!==config.wirelessMode)return;const choice=r.recommended?.[mode],saved=config[key],valid=r.items.find(n=>n.name===saved&&(mode==='hotspot'?n.hotspot:n.lan));if(choice&&!valid){await save(key,choice)}selected($('networkInterface'),r.items.map(n=>({value:n.name,label:n.name+(n.hotspot?' · 移动热点':n.lan?' · 局域网':'')+(n.ipv6?' · IPv6':'')})),config[key],'请选择网络接口');}
async function bluetooth(){const r=await call('bluetooth');if(r.ok)selected($('targetBluetooth'),r.devices.map(d=>({value:d.address,label:d.name+'（'+d.address.replace(/:/g,'').slice(-5)+'）'})),config.targetBluetooth,'自动（上次连接的iPhone）')}
function displayLimits(){const item=displayItems.find(d=>d.id===config.displayId)||displayItems.find(d=>d.primary);if(!item)return;$('displayId').value=String(item.id);$('width').max=item.width;$('height').max=item.height;$('width').disabled=config.fullScreen;$('height').disabled=config.fullScreen;$('fullScreen').checked=!!config.fullScreen;$('width').value=config.fullScreen?item.width:config.width;$('height').value=config.fullScreen?item.height:config.height;$('display-limit').textContent=(item.internal?'内建显示器':'外接显示器')+' · '+item.width+'×'+item.height+'物理像素'+(item.refreshRate?' · '+item.refreshRate+'Hz':'');const size=config.width+'x'+config.height;for(const option of $('resolutionPreset').options){if(/^\d+x\d+$/.test(option.value)){const [w,h]=option.value.split('x').map(Number);option.disabled=w>item.width||h>item.height}}const preset=[...$('resolutionPreset').options].some(o=>o.value===size&&!o.disabled);$('resolutionPreset').value=config.fullScreen?'native':resolutionChoice==='custom'?'custom':preset?size:'custom';$('custom-size').hidden=$('resolutionPreset').value!=='custom';$('request-pixels').textContent=$('width').value+'×'+$('height').value}
async function saveDisplay(values){values={...values,resolutionMode:resolutionChoice||'preset'};const r=await call('save',values);if(r.ok){Object.assign(config,values);displayLimits()}else displayLimits()}
async function displays(){const r=await call('displays');if(r.ok){displayItems=r.items;if(!r.items.some(d=>d.id===config.displayId))config.displayId=r.items.find(d=>d.internal)?.id||r.items.find(d=>d.primary)?.id||r.items[0]?.id;selected($('displayId'),r.items.map(d=>({value:d.id,label:d.label+' · '+d.width+'×'+d.height+(d.primary?' · 主显示器':'')})),config.displayId);displayLimits()}}
async function audioDevices(request=false){try{if(request){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}const list=await navigator.mediaDevices.enumerateDevices();selected($('outputDevice'),list.filter(d=>d.kind==='audiooutput'&&d.deviceId!=='default'&&d.deviceId!=='communications').map((d,i)=>({value:d.deviceId,label:d.label||`输出设备 ${i+1}`})),config.outputDevice,'系统默认设备');selected($('inputDevice'),list.filter(d=>d.kind==='audioinput'&&d.deviceId!=='default'&&d.deviceId!=='communications').map((d,i)=>({value:d.deviceId,label:d.label||`输入设备 ${i+1}`})),config.inputDevice,'系统默认设备')}catch{toast('Windows未允许麦克风访问，请检查系统隐私设置')}}
async function save(key,value){config[key]=value;const r=await call('save',{[key]:value});if(r.ok&&key==='theme')theme(value==='dark'||value==='system'&&(await winplay.call('state')).dark)}
document.querySelectorAll('.nav').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==button.dataset.page)}));
function format(ms){const s=Math.max(0,Math.floor((ms||0)/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function metadata(s,artChanged){playing=s;if(artChanged){if(artUrl)URL.revokeObjectURL(artUrl);artUrl=s.artwork?.length?URL.createObjectURL(new Blob([new Uint8Array(s.artwork)],{type:s.artwork[0]===137?'image/png':'image/jpeg'})):'';$('artwork').hidden=!artUrl;if(artUrl)$('artwork').src=artUrl;else $('artwork').removeAttribute('src')}
 $('track-title').textContent=s.title||'未上报歌名';$('track-artist').textContent=[s.artist,s.album].filter(Boolean).join(' · ');$('seek').max=s.durationMs||1;$('seek').disabled=!s.canSeek||!s.durationMs;position(s.positionMs)
 if('mediaSession' in navigator){if(!navigator.mediaSession.metadata)navigator.mediaSession.metadata=new MediaMetadata();const meta=navigator.mediaSession.metadata;meta.title=s.title;meta.artist=s.artist;meta.album=s.album;if(artChanged)meta.artwork=artUrl?[{src:artUrl,type:s.artwork?.[0]===137?'image/png':'image/jpeg'}]:[];navigator.mediaSession.playbackState=s.playing?'playing':'paused';for(const [name,index] of [['play',1],['pause',2],['previoustrack',5],['nexttrack',4]])navigator.mediaSession.setActionHandler(name,()=>winplay.input({command:'media',index}));try{navigator.mediaSession.setActionHandler('seekto',s.canSeek&&s.durationMs?event=>winplay.input({command:'seek',ms:Math.round(event.seekTime*1000)}):null)}catch{} }
}
function position(ms){$('seek').value=Math.min(playing.durationMs||1,ms||0);$('progress').textContent=format(ms)+' / '+format(playing.durationMs);if(navigator.mediaSession&&playing.durationMs>0){try{navigator.mediaSession.setPositionState({duration:playing.durationMs/1000,position:Math.min(playing.durationMs/1000,Math.max(0,(ms||0)/1000)),playbackRate:1})}catch{}}}
winplay.on(message=>{if(message.type==='close-behavior'){$('closeBehavior').value=message.value;config.closeBehavior=message.value}if(message.type==='appearance')theme(message.dark);if(message.type==='starting'||message.type==='started'){state(true);window.winplayAudio?.prepare(config).catch(()=>{})}if(message.type==='requested-fps'){$('fps-fallback').hidden=message.attempt>=message.requested;$('fps-fallback').textContent='当前已从'+message.requested+'fps回退至'+message.attempt+'fps'}if(message.type==='status'||message.type==='diagnostic'){if(message.type==='status'){$('status').textContent=message.status;$('status-detail').textContent=message.detail||''}logs.push(new Date().toLocaleTimeString()+'  '+message.status+(message.detail?'\n'+message.detail:''));$('logs').textContent=logs.slice(-100).join('\n')}
 if(message.type==='connected'){$('side-status').textContent='已收到视频';$('show-video').disabled=false}
 if(message.type==='stopped'){const last=logs[logs.length-1]||'';const failure=/失败|拒绝|未建立|超时|无法|没有检测|请选择|异常/.test(last);state(false);metadata({title:'',artist:'',album:'',playing:false,canSeek:false,durationMs:0,positionMs:0},true);if(navigator.mediaSession){navigator.mediaSession.metadata=null;navigator.mediaSession.playbackState='none';for(const action of ['play','pause','previoustrack','nexttrack','seekto']){try{navigator.mediaSession.setActionHandler(action,null)}catch{}}}if(!failure){$('status').textContent='接收已停止';$('status-detail').textContent='可以重新启动接收。'}}
 if(message.type==='metrics'){$('metric-request').textContent=message.requested+'fps';$('metric-attempt').textContent=running?message.attempt+'fps':'—';$('metric-received').textContent=running?message.receivedFps.toFixed(1)+'fps':'—';$('metric-decoded').textContent=running?(message.decodedFps||0).toFixed(1)+'fps':'—';if(message.decodedWidth)$('video-size').textContent=`实际解码尺寸：${message.decodedWidth}×${message.decodedHeight}`}
 if(message.type==='audio-config'&&message.opts.media){const o=message.opts;$('actual-media-format').textContent=(o.codec==='pcm'?'PCM/16位':o.codec==='aac-lc'?'AAC-LC':o.codec.toUpperCase())+' · '+o.clockRate/1000+'kHz · '+o.channels+'声道'}if(message.type==='stopped')$('actual-media-format').textContent='等待iPhone协商';if(message.type==='now-playing')metadata(message.state,message.artChanged);if(message.type==='position')position(message.positionMs)
 window.winplayAudio?.handle(message)
});
(async()=>{const r=await call('state');if(!r.ok)return;config=r.settings;resolutionChoice=config.resolutionMode;theme(r.dark);state(r.running);$('show-video').disabled=!(r.running&&r.stats?.decodedWidth);$('version').textContent=$('about-version').textContent=r.version;for(const item of r.diagnostics||[])logs.push(new Date(item.time).toLocaleTimeString()+'  '+item.status+(item.detail?'\n'+item.detail:''));if(logs.length)$('logs').textContent=logs.slice(-100).join('\n');$('auth-status').textContent=r.auth?'文件已就绪，等待iPhone验证':'缺少文件';
 for(const key of ['ssid','password','channel','fps','theme','closeBehavior']){$(key).value=config[fieldKey(key)];$(key).addEventListener('change',()=>save(fieldKey(key),['channel','width','height','fps'].includes(key)?Number($(key).value):$(key).value))}
 for(const key of ['targetBluetooth','networkInterface','inputDevice','outputDevice'])$(key).addEventListener('change',()=>save(fieldKey(key),key==='displayId'?Number($(key).value):$(key).value));
 for(const key of ['mediaVolume','callVolume']){$(key).value=Math.round(config[key]*100);$(key==='mediaVolume'?'media-label':'call-label').textContent=$(key).value+'%';$(key).addEventListener('input',()=>{$(key==='mediaVolume'?'media-label':'call-label').textContent=$(key).value+'%';save(key,Number($(key).value)/100)})}
 $('lanAccessPointMac').addEventListener('change',()=>save('lanAccessPointMac',$('lanAccessPointMac').value.trim()));$('wirelessMode').addEventListener('change',async()=>{await save('wirelessMode',$('wirelessMode').value);wirelessFields();await networks()});
 wirelessFields();
 $('resolutionPreset').onchange=async()=>{const value=$('resolutionPreset').value;resolutionChoice=value;if(value==='native')await saveDisplay({fullScreen:true});else if(value==='custom')await saveDisplay({fullScreen:false});else{const [width,height]=value.split('x').map(Number);await saveDisplay({fullScreen:false,width,height})}};
 $('width').onchange=$('height').onchange=()=>saveDisplay({width:Number($('width').value),height:Number($('height').value)});$('fullScreen').onchange=()=>saveDisplay({fullScreen:$('fullScreen').checked});$('displayId').onchange=()=>{const item=displayItems.find(d=>d.id===Number($('displayId').value));if(item)saveDisplay({displayId:item.id})};
 $('start').onclick=async()=>{const active=running;$('start').disabled=true;try{await window.winplayAudio.prepare(config);await call(active?'restart':'start')}finally{$('start').disabled=false}};$('stop').onclick=()=>call('stop');$('show-video').onclick=()=>call('show-video');$('audioEnabled').checked=config.audioEnabled!==false;$('audioEnabled').onchange=()=>save('audioEnabled',$('audioEnabled').checked);$('open-auth').onclick=()=>call('open-auth');$('open-log').onclick=()=>call('open-log');$('refresh-status').onclick=async()=>{const result=await call('state');if(result.ok){$('auth-status').textContent=result.auth?'文件已就绪，等待iPhone验证':'缺少文件';$('logs').textContent=result.diagnostics.map(d=>new Date(d.time).toLocaleTimeString()+'  '+d.status+(d.detail?'\n'+d.detail:'')).join('\n')||'暂无日志'}};
 $('hotspot-settings').onclick=()=>call(config.wirelessMode==='lan'?'settings-location':'settings-hotspot');$('bluetooth-settings').onclick=()=>call('settings-bluetooth');$('refresh-bt').onclick=bluetooth;$('refresh-network').onclick=networks;$('refresh-displays').onclick=displays;$('refresh-audio').onclick=()=>audioDevices(true);
 $('import-auth').onclick=async()=>{const r=await call('import-auth');if(r.ok){$('auth-status').textContent='认证文件已更新';toast('认证材料已用Windows DPAPI保护保存')}};$('export-diagnostics').onclick=()=>call('export-diagnostics');
 $('previous').onclick=()=>winplay.input({command:'media',index:5});$('playpause').onclick=()=>winplay.input({command:'media',index:3});$('next').onclick=()=>winplay.input({command:'media',index:4});$('seek').addEventListener('change',()=>winplay.input({command:'seek',ms:Math.round(Number($('seek').value))}));
 $('ssid').addEventListener('input',()=>{$('read-password').disabled=!$('ssid').value.trim()});const networkResult=text=>{$('network-result').hidden=false;$('network-result').textContent=text};$('read-network').onclick=async()=>{const r=await winplay.call('read-network');if(!r.ok){networkResult(r.error);return}$('ssid').value=r.ssid;await save(fieldKey('ssid'),r.ssid);if(r.channel>=1&&r.channel<=196){$('channel').value=r.channel;await save(fieldKey('channel'),r.channel)}$('read-password').disabled=false;networkResult('已读取当前Wi-Fi名称和信道。请确认网络接口与密码。')};$('read-password').onclick=async()=>{const button=$('read-password');button.disabled=true;button.textContent='正在读取密码…';try{const r=await winplay.call('read-password',{ssid:$('ssid').value});if(r.ok){$('password').value=r.password;await save(fieldKey('password'),r.password);networkResult('已读取Windows保存的共享密码。')}else networkResult(r.error)}finally{button.textContent='读取已保存密码';button.disabled=!$('ssid').value.trim()}};$('collapse-sidebar').onclick=()=>document.body.classList.toggle('sidebar-collapsed');const resizer=$('sidebar-resizer');resizer.onpointerdown=e=>{resizer.setPointerCapture(e.pointerId);resizer.onpointermove=event=>{document.querySelector('aside').style.width=Math.max(150,Math.min(200,event.clientX))+'px'};resizer.onpointerup=()=>{resizer.onpointermove=null}};let refreshing=false;window.addEventListener('focus',async()=>{if(refreshing)return;refreshing=true;try{await Promise.all([networks(),displays(),audioDevices(),bluetooth()])}finally{refreshing=false}});await Promise.all([networks(),displays(),audioDevices(),bluetooth()]);navigator.mediaDevices.addEventListener('devicechange',()=>audioDevices());
})().catch(()=>toast('界面初始化失败，请重新打开WinPlay'));
