(function(){let context,destination,master,settings={},audio=document.getElementById('system-audio');const streams=new Map(),mics=new Map(),micGeneration=new Map();
 const error=reason=>winplay.input({command:'audio-error',reason});
 async function prepare(s){settings={...s};if(!context||context.state==='closed'){context=new AudioContext({latencyHint:'interactive'});destination=context.createMediaStreamDestination();master=context.createGain();master.connect(destination);audio.srcObject=destination.stream}master.gain.value=settings.audioEnabled===false?0:1;await context.resume();await route();await audio.play().catch(()=>{})}
 async function route(){if(!audio.setSinkId)return;try{await audio.setSinkId(settings.outputDevice||'')}catch{await audio.setSinkId('');}}
 async function open(m){if(!context)await prepare(settings);close(m.id);const gain=context.createGain();gain.connect(master);const s={opts:m.opts,gain,decoder:null,origin:null,firstSample:null,active:false,queue:[],seen:new Set(),sources:new Set(),timeline:new WinPlayAudioTimeline(m.opts.clockRate,m.opts.realtime ? .08 : Math.min(.5,Math.max(.15,(m.opts.latencyMs||0)/1000)))};streams.set(m.id,s);if(m.opts.codec==='pcm')return;
  const config=m.opts.codec==='opus'?{codec:'opus',sampleRate:m.opts.clockRate,numberOfChannels:m.opts.channels}:{codec:'mp4a.40.2',sampleRate:m.opts.clockRate,numberOfChannels:m.opts.channels,description:new Uint8Array([(2<<3)|((m.opts.clockRate===48000?3:4)>>1),(((m.opts.clockRate===48000?3:4)&1)<<7)|(m.opts.channels<<3)])};
  try{const supported=await AudioDecoder.isConfigSupported(config);if(!supported.supported)throw new Error('解码器不支持'+m.opts.codec);if(streams.get(m.id)!==s)return;s.decoder=new AudioDecoder({output(data){try{if(streams.get(m.id)!==s||!s.active)return;const buffer=context.createBuffer(data.numberOfChannels,data.numberOfFrames,data.sampleRate);for(let c=0;c<data.numberOfChannels;c++)data.copyTo(buffer.getChannelData(c),{planeIndex:c,format:'f32-planar'});play(s,buffer,Math.round(data.timestamp*m.opts.clockRate/1000000))}finally{data.close()}},error(e){error(e.message)}});s.decoderConfig=config;s.decoder.configure(config)}catch(e){error('音频解码器：'+e.message)}
 }
 function clearSources(s){for(const source of s.sources){try{source.stop()}catch{}source.disconnect()}s.sources.clear()}
 function play(s,buffer,sampleOffset){if(!s.active)return;const plan=s.timeline.plan(sampleOffset,buffer.duration,context.currentTime);if(!plan)return;if(plan.reset)clearSources(s);
  const source=context.createBufferSource();source.buffer=buffer;source.playbackRate.value=1;source.connect(s.gain);s.sources.add(source);source.onended=()=>{s.sources.delete(source);source.disconnect()};source.start(plan.when,plan.trim);
 }
 function packet(m){const s=streams.get(m.id);if(!s||!s.active)return;if(s.seen.has(m.sequence))return;s.seen.add(m.sequence);if(s.seen.size>128)s.seen.delete(s.seen.values().next().value);if(s.firstSample===null)s.firstSample=m.sample;const offset=(m.sample-s.firstSample)>>>0;if(offset>0x7fffffff)return;s.queue.push({data:new Uint8Array(m.data),offset,received:performance.now()});if(s.queue.length>64)s.queue.shift();s.queue.sort((a,b)=>a.offset-b.offset)}
 function pump(){for(const s of streams.values()){if(s.opts.codec!=='pcm'&&!s.decoder)continue;while(s.queue.length){if(performance.now()-s.queue[0].received<30)break;if(s.opts.codec!=='pcm'&&(s.decoder.state!=='configured'||s.decoder.decodeQueueSize>=16))break;const p=s.queue.shift();const timestamp=Math.round(p.offset*1000000/s.opts.clockRate);try{if(s.opts.codec==='pcm'){const samples=Math.floor(p.data.length/2/s.opts.channels),buffer=context.createBuffer(s.opts.channels,samples,s.opts.clockRate),view=new DataView(p.data.buffer,p.data.byteOffset,p.data.byteLength);for(let c=0;c<s.opts.channels;c++){const plane=buffer.getChannelData(c);for(let i=0;i<samples;i++)plane[i]=view.getInt16((i*s.opts.channels+c)*2,false)/32768}play(s,buffer,p.offset)}else if(s.decoder.state==='configured'&&s.decoder.decodeQueueSize<64)s.decoder.decode(new EncodedAudioChunk({type:'key',timestamp,data:p.data}))}catch(e){error('音频包解码：'+e.message)}}}}
 function close(id){const s=streams.get(id);if(!s)return;s.active=false;s.decoder?.close();clearSources(s);s.gain.disconnect();streams.delete(id)}
 async function micOpen(m){micClose(m.id);const generation=micGeneration.get(m.id);const o=m.opts;let stream,micContext,encoder;try{const devices=await navigator.mediaDevices.enumerateDevices(),selected=devices.some(d=>d.kind==='audioinput'&&d.deviceId===settings.inputDevice)?settings.inputDevice:'';stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:selected?{exact:selected}:undefined,channelCount:o.channels,echoCancellation:true,noiseSuppression:true}});micContext=new AudioContext({sampleRate:o.sampleRate});await micContext.audioWorklet.addModule('capture-worklet.js');const frames=Math.round(o.sampleRate*o.frameMs/1000),node=new AudioWorkletNode(micContext,'winplay-capture',{processorOptions:{frames,channels:o.channels}}),source=micContext.createMediaStreamSource(stream),silence=micContext.createGain();silence.gain.value=0;source.connect(node);node.connect(silence).connect(micContext.destination);let timestamp=0;
  if(o.codec==='opus'){const config={codec:'opus',sampleRate:o.sampleRate,numberOfChannels:o.channels,bitrate:o.bitrate,opus:{frameDuration:o.frameMs*1000}};const supported=await AudioEncoder.isConfigSupported(config);if(!supported.supported)throw new Error('Windows Opus编码器不支持协商参数');encoder=new AudioEncoder({output(chunk){const data=new Uint8Array(chunk.byteLength);chunk.copyTo(data);winplay.input({command:'mic',id:m.id,data,samples:Math.round(chunk.duration*o.sampleRate/1000000)})},error(e){error(e.message)}});encoder.configure(config)}
  if(micGeneration.get(m.id)!==generation){stream.getTracks().forEach(t=>t.stop());micContext.close();encoder?.close();node.disconnect();source.disconnect();return}
  node.port.onmessage=event=>{const values=event.data;if(o.codec==='pcm'){const data=new Uint8Array(values.length*2),view=new DataView(data.buffer);for(let i=0;i<values.length;i++)view.setInt16(i*2,Math.round(Math.max(-1,Math.min(1,values[i]))*32767),false);winplay.input({command:'mic',id:m.id,data,samples:frames})}else if(encoder.state==='configured'&&encoder.encodeQueueSize<8){const data=new AudioData({format:'f32',sampleRate:o.sampleRate,numberOfFrames:frames,numberOfChannels:o.channels,timestamp,data:values});encoder.encode(data);data.close()}timestamp+=o.frameMs*1000};mics.set(m.id,{stream,context:micContext,encoder,node,source,opts:o});await micContext.resume();
 }catch(e){stream?.getTracks().forEach(t=>t.stop());micContext?.close();encoder?.close();error('麦克风：'+e.message)}}
 function micClose(id){micGeneration.set(id,(micGeneration.get(id)||0)+1);const m=mics.get(id);if(!m)return;m.node.port.onmessage=null;m.node.disconnect();m.source.disconnect();m.stream.getTracks().forEach(t=>t.stop());m.encoder?.close();m.context.close();mics.delete(id)}
 async function devices(m){const previous=settings.inputDevice;settings.inputDevice=m.inputDevice;settings.outputDevice=m.outputDevice;await route();if(previous!==settings.inputDevice){const pending=[...mics].map(([id,mic])=>({id,opts:mic.opts}));for(const mic of pending)micOpen(mic)}}
 function handle(m){if(m.type==='audio-enabled'){settings.audioEnabled=m.enabled;if(master)master.gain.setTargetAtTime(m.enabled?1:0,context.currentTime,.02)}if(m.type==='audio-config')open(m).catch(e=>error(e.message));if(m.type==='audio')packet(m);if(m.type==='audio-active'){const s=streams.get(m.id);if(s&&s.active!==m.active){s.active=m.active;s.queue.length=0;s.seen.clear();s.firstSample=null;s.timeline.reset();clearSources(s);if(s.decoder?.state==='configured'){s.decoder.reset();s.decoder.configure(s.decoderConfig)}}}if(m.type==='audio-volume'){const s=streams.get(m.id);if(s)s.gain.gain.setTargetAtTime(m.level,context.currentTime,.02)}if(m.type==='audio-close')close(m.id);if(m.type==='mic-open')micOpen(m);if(m.type==='mic-close')micClose(m.id);if(m.type==='audio-devices')devices(m);if(m.type==='stopped'){for(const id of [...streams.keys()])close(id);for(const id of [...mics.keys()])micClose(id);audio.pause();context?.suspend()}}
 navigator.mediaDevices.addEventListener('devicechange',async()=>{await route();const pending=[...mics].map(([id,mic])=>({id,opts:mic.opts}));for(const mic of pending)micOpen(mic)});setInterval(pump,20);window.winplayAudio={prepare,handle};
})();

