(function(){let context,master,settings={},routeChain=Promise.resolve();const streams=new Map(),mics=new Map(),micGeneration=new Map();
 const error=reason=>winplay.input({command:'audio-error',reason});
 const wallTime=()=>typeof performance==='object'?performance.now()/1000:Date.now()/1000;
 function freshTiming(){return {outputs:0,frames:[],rate:[],rtp:[],gap:[],lead:[],wait:[],queueMax:0,decodeMax:0,pumpGapMs:0,lastPump:null,startContext:context.currentTime,startWall:wallTime()}}
 function range(values,value){if(!Number.isFinite(value))return;if(values.length===0)values.push(value,value);else{values[0]=Math.min(values[0],value);values[1]=Math.max(values[1],value)}}
 async function prepare(s){settings={...s};if(!context||context.state==='closed'){context=new AudioContext({sampleRate:48000,latencyHint:'playback'});master=context.createGain();master.connect(context.destination)}master.gain.value=settings.audioEnabled===false?0:1;await route();await context.resume()}
 async function route(){if(!context)return;const target=settings.outputDevice||'';routeChain=routeChain.catch(()=>{}).then(async()=>{if(!context.setSinkId){if(target)error('当前音频输出不支持设备选择');return}if(context.sinkId===target)return;try{await context.setSinkId(target)}catch{await context.setSinkId('');error('所选音频设备不可用，已改用系统默认设备')}});return routeChain}
 async function open(m){if(!context)await prepare(settings);close(m.id);const gain=context.createGain();gain.connect(master);const s={id:m.id,opts:m.opts,gain,decoder:null,packetClock:null,timing:freshTiming(),epoch:0,closed:false,lastOutput:null,lastSubmittedOffset:-1,firstSample:null,lastSample:null,lastSequence:null,lastDecodedSequence:null,counts:{late:0,rebuffer:0,overflow:0,timestampReset:0,missing:0,discontinuity:0,mappingReset:0},reported:0,active:false,queue:[],seen:new Set(),sources:new Set(),timeline:new WinPlayAudioTimeline(m.opts.clockRate,m.opts.realtime ? .1 : Math.min(1.5,Math.max(.25,(m.opts.latencyMs||1000)/1000)))};streams.set(m.id,s);if(m.opts.codec==='pcm')return;
  const config=m.opts.codec==='opus'?{codec:'opus',sampleRate:m.opts.clockRate,numberOfChannels:m.opts.channels}:{codec:'mp4a.40.2',sampleRate:m.opts.clockRate,numberOfChannels:m.opts.channels,description:new Uint8Array([(2<<3)|((m.opts.clockRate===48000?3:4)>>1),(((m.opts.clockRate===48000?3:4)&1)<<7)|(m.opts.channels<<3)])};
  try{const supported=await AudioDecoder.isConfigSupported(config);if(!supported.supported)throw new Error('解码器不支持'+m.opts.codec);if(streams.get(m.id)!==s)return;s.decoderConfig=config;configureDecoder(s)}catch(e){error('音频解码器：'+e.message)}
 }
 function configureDecoder(s){const epoch=s.epoch;s.packetClock=s.opts.codec==='aac-lc'?new WinPlayAudioTimeline.PacketClock(s.opts.clockRate):null;const decoder=new AudioDecoder({output(data){try{if(streams.get(s.id)!==s||s.decoder!==decoder||s.epoch!==epoch||!s.active)return;const spans=s.packetClock?s.packetClock.take(data.numberOfFrames,data.sampleRate):[{offset:Math.round(data.timestamp*s.opts.clockRate/1000000),frameOffset:0,frames:data.numberOfFrames}],timing=s.timing;timing.outputs++;range(timing.frames,data.numberOfFrames);range(timing.rate,data.sampleRate);range(timing.gap,(spans[0].offset/s.opts.clockRate-data.timestamp/1000000)*1000);range(timing.lead,(s.timeline.origin+spans[0].offset/s.opts.clockRate-context.currentTime)*1000);for(const span of spans){const buffer=context.createBuffer(data.numberOfChannels,span.frames,data.sampleRate);for(let c=0;c<data.numberOfChannels;c++)data.copyTo(buffer.getChannelData(c),{planeIndex:c,frameOffset:span.frameOffset,frameCount:span.frames,format:'f32-planar'});play(s,buffer,span.offset)}}catch(e){if(streams.get(s.id)===s&&s.decoder===decoder&&s.epoch===epoch)recoverDecoder(s,e.message)}finally{data.close()}},error(e){if(streams.get(s.id)===s&&s.decoder===decoder&&s.epoch===epoch)recoverDecoder(s,e.message)}});s.decoder=decoder;decoder.configure(s.decoderConfig)}
 function recoverDecoder(s,reason){s.counts.mappingReset++;s.epoch++;if(s.decoder&&s.decoder.state!=='closed')s.decoder.close();s.decoder=null;s.packetClock?.reset();if(s.counts.mappingReset<=3&&s.active&&!s.closed)configureDecoder(s);else error('音频访问单元无法匹配，请重新连接：'+reason)}
 const edgeSeconds=.003;
 function disposeSource(s,entry){s.sources.delete(entry);if(s.lastOutput===entry)s.lastOutput=null;entry.source.disconnect();entry.envelope.disconnect();if(s.closed&&s.sources.size===0)s.gain.disconnect()}
 function clearSources(s){const now=context.currentTime;s.lastOutput=null;for(const entry of [...s.sources]){
  if(entry.when>now||entry.end<=now){try{entry.source.stop()}catch{}disposeSource(s,entry);continue}
  const parameter=entry.envelope.gain,stop=Math.min(entry.end,now+edgeSeconds);
  if(parameter.cancelAndHoldAtTime)parameter.cancelAndHoldAtTime(now);else{const head=entry.fadeIn?Math.min(1,Math.max(0,(now-entry.when)/entry.fadeIn)):1,tail=entry.tailCancelled?1:Math.min(1,Math.max(0,(entry.end-now)/(entry.end-entry.fadeStart)));parameter.cancelScheduledValues(now);parameter.setValueAtTime(Math.min(head,tail),now)}
  parameter.linearRampToValueAtTime(0,stop);try{entry.source.stop(stop)}catch{disposeSource(s,entry)}
 }}
 function play(s,buffer,sampleOffset){if(!s.active)return;const hadAudio=s.timeline.offset>=0,now=context.currentTime,plan=s.timeline.plan(sampleOffset,buffer.duration,now);if(!plan){s.counts.late++;return}if(plan.reset){if(s.sources.size)s.counts.rebuffer++;clearSources(s)}
  const previous=s.lastOutput,contiguous=!!previous&&Math.abs(previous.end-plan.when)<.5/context.sampleRate&&plan.trim===0&&now<previous.fadeStart;
  if(contiguous){previous.envelope.gain.cancelScheduledValues(previous.fadeStart);previous.envelope.gain.setValueAtTime(1,previous.fadeStart);previous.tailCancelled=true}else if(hadAudio||plan.trim>0)s.counts.discontinuity++;
  const source=context.createBufferSource(),envelope=context.createGain(),duration=buffer.duration-plan.trim,end=plan.when+duration,edge=Math.min(edgeSeconds,duration/2),entry={source,envelope,when:plan.when,end,fadeStart:end-edge,fadeIn:contiguous?0:edge,tailCancelled:false};
  // The next timely contiguous frame cancels this tail before it can play.
  // Only actual starts, starvation, loss and resets retain the short edge ramp.
  envelope.gain.setValueAtTime(contiguous?1:0,plan.when);if(!contiguous)envelope.gain.linearRampToValueAtTime(1,plan.when+edge);envelope.gain.setValueAtTime(1,entry.fadeStart);envelope.gain.linearRampToValueAtTime(0,end);
  source.buffer=buffer;source.playbackRate.value=1;source.connect(envelope);envelope.connect(s.gain);s.sources.add(entry);s.lastOutput=entry;source.onended=()=>disposeSource(s,entry);source.start(plan.when,plan.trim);
 }
 function packet(m){const s=streams.get(m.id);if(!s||!s.active)return;if(s.lastSample!==null&&s.lastSequence!==null){const step=(m.sequence-s.lastSequence)&65535,delta=(m.sample-s.lastSample)|0;if(step>0&&step<32768&&delta<-s.opts.clockRate/2){resetStream(s);s.counts.timestampReset++}}if(s.seen.has(m.sequence))return;s.seen.add(m.sequence);if(s.seen.size>128)s.seen.delete(s.seen.values().next().value);if(s.firstSample===null){s.firstSample=m.sample;s.timeline.anchor(context.currentTime);}if(s.lastSequence===null||((m.sequence-s.lastSequence)&65535)<32768){s.lastSequence=m.sequence;s.lastSample=m.sample;}let offset=(m.sample-s.firstSample)>>>0;if(offset>0x7fffffff){const back=(s.firstSample-m.sample)>>>0;if(s.lastSubmittedOffset<0&&back<s.opts.clockRate){s.firstSample=m.sample;s.timeline.origin-=back/s.opts.clockRate;for(const p of s.queue)p.offset+=back;offset=0}else{s.counts.late++;return}}s.queue.push({data:new Uint8Array(m.data),offset,sequence:m.sequence,arrival:wallTime()});if(s.queue.length>128){s.queue.shift();s.counts.overflow++;}s.queue.sort((a,b)=>a.offset-b.offset)}
 function pump(){for(const s of streams.values()){const timing=s.timing,now=context.currentTime;if(timing.lastPump!==null)timing.pumpGapMs=Math.max(timing.pumpGapMs,(now-timing.lastPump)*1000);timing.lastPump=now;timing.queueMax=Math.max(timing.queueMax,s.queue.length);timing.decodeMax=Math.max(timing.decodeMax,s.decoder?.decodeQueueSize||0);if(s.opts.codec!=='pcm'&&!s.decoder)continue;while(s.queue.length){if(!s.timeline.ready(s.queue[0].offset,context.currentTime,s.opts.realtime ? .04 : .1))break;if(s.opts.codec!=='pcm'&&(!s.decoder||s.decoder.state!=='configured'||s.decoder.decodeQueueSize>=16))break;const p=s.queue.shift();range(timing.wait,(wallTime()-p.arrival)*1000);if(p.offset<=s.lastSubmittedOffset){s.counts.late++;continue}if(s.lastDecodedSequence!==null){const gap=(p.sequence-s.lastDecodedSequence)&65535;if(gap>1&&gap<32768)s.counts.missing+=gap-1;if(gap===1)range(timing.rtp,p.offset-s.lastSubmittedOffset)}s.lastDecodedSequence=p.sequence;s.lastSubmittedOffset=p.offset;const timestamp=Math.round(p.offset*1000000/s.opts.clockRate);try{if(s.opts.codec==='pcm'){const samples=Math.floor(p.data.length/2/s.opts.channels);if(samples===0)continue;const buffer=context.createBuffer(s.opts.channels,samples,s.opts.clockRate),view=new DataView(p.data.buffer,p.data.byteOffset,p.data.byteLength);for(let c=0;c<s.opts.channels;c++){const plane=buffer.getChannelData(c);for(let i=0;i<samples;i++)plane[i]=view.getInt16((i*s.opts.channels+c)*2,false)/32768}play(s,buffer,p.offset)}else{try{s.packetClock?.submit(p.offset,p.sequence)}catch(e){recoverDecoder(s,e.message);if(!s.decoder)continue;s.packetClock?.submit(p.offset,p.sequence)}s.decoder.decode(new EncodedAudioChunk({type:'key',timestamp,data:p.data}))}}catch(e){if(s.opts.codec!=='pcm')recoverDecoder(s,e.message);else error('音频包解码：'+e.message)}}}}
 function resetStream(s){s.epoch++;s.queue.length=0;s.seen.clear();s.firstSample=null;s.lastSample=null;s.lastSequence=null;s.lastDecodedSequence=null;s.lastSubmittedOffset=-1;s.packetClock?.reset();s.timing=freshTiming();s.timeline.reset();clearSources(s);if(s.decoder){if(s.decoder.state!=='closed')s.decoder.close();s.decoder=null;if(s.decoderConfig)configureDecoder(s)}}
 function close(id){const s=streams.get(id);if(!s)return;s.active=false;s.closed=true;s.epoch++;s.packetClock?.reset();if(s.decoder&&s.decoder.state!=='closed')s.decoder.close();clearSources(s);if(s.sources.size===0)s.gain.disconnect();streams.delete(id)}
 async function micOpen(m){micClose(m.id);const generation=micGeneration.get(m.id);const o=m.opts;let stream,micContext,encoder;try{const devices=await navigator.mediaDevices.enumerateDevices(),selected=devices.some(d=>d.kind==='audioinput'&&d.deviceId===settings.inputDevice)?settings.inputDevice:'';stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:selected?{exact:selected}:undefined,channelCount:o.channels,echoCancellation:true,noiseSuppression:true}});micContext=new AudioContext({sampleRate:o.sampleRate});await micContext.audioWorklet.addModule('capture-worklet.js');const frames=Math.round(o.sampleRate*o.frameMs/1000),node=new AudioWorkletNode(micContext,'winplay-capture',{processorOptions:{frames,channels:o.channels}}),source=micContext.createMediaStreamSource(stream),silence=micContext.createGain();silence.gain.value=0;source.connect(node);node.connect(silence).connect(micContext.destination);let timestamp=0;
  if(o.codec==='opus'){const config={codec:'opus',sampleRate:o.sampleRate,numberOfChannels:o.channels,bitrate:o.bitrate,opus:{frameDuration:o.frameMs*1000}};const supported=await AudioEncoder.isConfigSupported(config);if(!supported.supported)throw new Error('Windows Opus编码器不支持协商参数');encoder=new AudioEncoder({output(chunk){const data=new Uint8Array(chunk.byteLength);chunk.copyTo(data);winplay.input({command:'mic',id:m.id,data,samples:Math.round(chunk.duration*o.sampleRate/1000000)})},error(e){error(e.message)}});encoder.configure(config)}
  if(micGeneration.get(m.id)!==generation){stream.getTracks().forEach(t=>t.stop());micContext.close();encoder?.close();node.disconnect();source.disconnect();return}
  node.port.onmessage=event=>{const values=event.data;if(o.codec==='pcm'){const data=new Uint8Array(values.length*2),view=new DataView(data.buffer);for(let i=0;i<values.length;i++)view.setInt16(i*2,Math.round(Math.max(-1,Math.min(1,values[i]))*32767),false);winplay.input({command:'mic',id:m.id,data,samples:frames})}else if(encoder.state==='configured'&&encoder.encodeQueueSize<8){const data=new AudioData({format:'f32',sampleRate:o.sampleRate,numberOfFrames:frames,numberOfChannels:o.channels,timestamp,data:values});encoder.encode(data);data.close()}timestamp+=o.frameMs*1000};mics.set(m.id,{stream,context:micContext,encoder,node,source,opts:o});await micContext.resume();
 }catch(e){stream?.getTracks().forEach(t=>t.stop());micContext?.close();encoder?.close();error('麦克风：'+e.message)}}
 function micClose(id){micGeneration.set(id,(micGeneration.get(id)||0)+1);const m=mics.get(id);if(!m)return;m.node.port.onmessage=null;m.node.disconnect();m.source.disconnect();m.stream.getTracks().forEach(t=>t.stop());m.encoder?.close();m.context.close();mics.delete(id)}
 async function devices(m){const previous=settings.inputDevice;settings.inputDevice=m.inputDevice;settings.outputDevice=m.outputDevice;await route();if(previous!==settings.inputDevice){const pending=[...mics].map(([id,mic])=>({id,opts:mic.opts}));for(const mic of pending)micOpen(mic)}}
 function handle(m){if(m.type==='audio-enabled'){settings.audioEnabled=m.enabled;if(master)master.gain.setTargetAtTime(m.enabled?1:0,context.currentTime,.02)}if(m.type==='audio-config')open(m).catch(e=>error(e.message));if(m.type==='audio')packet(m);if(m.type==='audio-active'){const s=streams.get(m.id);if(s&&s.active!==m.active){s.active=m.active;resetStream(s)}}if(m.type==='audio-volume'){const s=streams.get(m.id);if(s)s.gain.gain.setTargetAtTime(m.level,context.currentTime,.02)}if(m.type==='audio-close')close(m.id);if(m.type==='mic-open')micOpen(m);if(m.type==='mic-close')micClose(m.id);if(m.type==='audio-devices')devices(m);if(m.type==='stopped'){for(const id of [...streams.keys()])close(id);for(const id of [...mics.keys()])micClose(id);context?.suspend()}}
 navigator.mediaDevices.addEventListener('devicechange',async()=>{await route();const pending=[...mics].map(([id,mic])=>({id,opts:mic.opts}));for(const mic of pending)micOpen(mic)});setInterval(pump,10);setInterval(()=>{for(const s of streams.values()){const total=Object.values(s.counts).reduce((a,b)=>a+b,0);if(total>s.reported){s.reported=total;winplay.input({command:'audio-diagnostic',reason:JSON.stringify({codec:s.opts.codec,clockRate:s.opts.clockRate,outputRate:context.sampleRate,bufferMs:Math.round(s.timeline.delay*1000),...s.counts})})}const t=s.timing;if(t.outputs){const rounded=values=>values.map(v=>Math.round(v*10)/10);winplay.input({command:'audio-diagnostic',reason:JSON.stringify({phase:'timing',codec:s.opts.codec,frames:t.frames,rate:t.rate,rtpStep:t.rtp,ptsGapMs:rounded(t.gap),leadMs:rounded(t.lead),waitMs:rounded(t.wait),pending:s.packetClock?.frames||0,queueMax:t.queueMax,decodeMax:t.decodeMax,pumpGapMs:Math.round(t.pumpGapMs),clockDriftMs:Math.round((context.currentTime-t.startContext-wallTime()+t.startWall)*1000),state:context.state,mics:mics.size})});s.timing=freshTiming()}}},10000);window.winplayAudio={prepare,handle,outputState:()=>({state:context?.state,sampleRate:context?.sampleRate,sinkId:context?.sinkId,direct:!!context&&!!master})};
})();

