(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.WinPlayI18n=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  // Translate only application-owned phrases. Device names, media titles and raw logs stay untouched.
  const entries=[
    ['热点信道必须为0—196，0表示自动','熱點頻道必須為0—196，0表示自動','Hotspot channel must be between 0 and 196. Channel 0 means automatic'],
    ['Windows未提供移动热点的实际信道，已使用0自动发现','Windows未提供行動熱點的實際頻道，已使用0自動探索','Windows does not expose the mobile hotspot channel. Channel 0 uses automatic discovery'],
    ['热点名称已读取，但无法读取热点密码，请手动填写','熱點名稱已讀取，但無法讀取熱點密碼，請手動填寫','The hotspot name was read, but its password could not be read. Enter the password manually'],
    ['热点尚未开启，已读取Windows保存的热点配置','熱點尚未開啟，已讀取Windows儲存的熱點設定','The hotspot is off. Read the hotspot settings saved by Windows'],
    ['当前热点共享网卡尚未就绪，热点配置已读取','目前熱點共用網路卡尚未就緒，熱點設定已讀取','The shared hotspot adapter is not ready. The hotspot settings were read'],
    ['无法读取当前Wi-Fi信道，已保留现有信道设置','無法讀取目前Wi-Fi頻道，已保留現有頻道設定','The current Wi-Fi channel could not be read. The existing channel setting was kept'],
    ['当前网络已读取，但无法读取已保存密码，请确认共享密码后手动填写','目前網路已讀取，但無法讀取已儲存密碼，請確認共用密碼後手動填寫','The current network was read, but its saved password could not be read. Confirm the shared password and enter it manually'],
    ['无法读取Windows移动热点配置，请在系统设置中核对热点名称和密码','無法讀取Windows行動熱點設定，請在系統設定中核對熱點名稱和密碼','Could not read Windows mobile hotspot settings. Check the hotspot name and password in system settings'],
    ['读取当前网络失败，请确认已连接Wi-Fi并允许系统读取网络信息','讀取目前網路失敗，請確認已連接Wi-Fi並允許系統讀取網路資訊','Could not read the current network. Connect to Wi-Fi and allow Windows to read network information'],
    ['无线模式无效','無線模式無效','Invalid wireless mode'],
    ['Windows移动热点未开启，请开启热点后重试','Windows行動熱點未開啟，請開啟熱點後重試','Windows mobile hotspot is off. Turn it on and try again.'],
    ['Windows移动热点正在启动，请等待共享接口就绪','Windows行動熱點正在啟動，請等待共用介面就緒','Windows mobile hotspot is starting. Wait for its shared adapter to become ready.'],
    ['检测到多个可能的热点接口，无法确认当前共享接口，请检查Windows移动热点设置后重试','偵測到多個可能的熱點介面，無法確認目前共用介面，請檢查Windows行動熱點設定後重試','More than one possible hotspot adapter was detected. Check Windows mobile hotspot settings and try again.'],
    ['正在切换CarPlay连接地址','正在切換CarPlay連接位址','Trying another CarPlay connection address'],['改用IPv6重试；Windows网络设置保持不变。','改用IPv6重試；Windows網路設定保持不變。','Retrying with IPv6; Windows network settings remain unchanged.'],['改用IPv4重试；Windows网络设置保持不变。','改用IPv4重試；Windows網路設定保持不變。','Retrying with IPv4; Windows network settings remain unchanged.'],['CarPlay连接参数重发失败','CarPlay連接參數重傳失敗','Could not resend CarPlay connection parameters'],['仍在等待iPhone网络连接','仍在等待iPhone網路連接','Still waiting for the iPhone network connection'],
    ['若iPhone已连接同一Wi-Fi却仍未建立CarPlay，可在iPhone上断开该Wi-Fi再重新加入，或改用本机移动热点。','若iPhone已連接同一Wi-Fi卻仍未建立CarPlay，可在iPhone上中斷該Wi-Fi再重新加入，或改用本機行動熱點。','If the iPhone is already on the same Wi-Fi but CarPlay has not connected, disconnect that Wi-Fi on the iPhone and rejoin it, or use the Windows mobile hotspot.'],['请确认iPhone已加入Windows移动热点，并检查当前网络接口和防火墙。','請確認iPhone已加入Windows行動熱點，並檢查目前網路介面和防火牆。','Make sure the iPhone has joined the Windows mobile hotspot, and check the network adapter and firewall.'],
    ['iPhone控制服务探测失败，请检查无线网络与防火墙','iPhone控制服務探測失敗，請檢查無線網路與防火牆','Could not reach the iPhone control service. Check the wireless network and firewall.'],
    ['当前Wi-Fi与配置不一致，请读取当前网络并重新确认共享密码','目前Wi-Fi與設定不一致，請讀取目前網路並重新確認共用密碼','The current Wi-Fi does not match the configuration. Read the current network and confirm its shared password.'],
    ['iPhone网络连接超时','iPhone網路連接逾時','iPhone network connection timed out'],['蓝牙认证已通过，但手机尚未连接接收端。请读取当前网络并检查防火墙或路由器的客户端隔离设置。','藍牙驗證已通過，但手機尚未連接接收端。請讀取目前網路並檢查防火牆或路由器的用戶端隔離設定。','Bluetooth authentication passed, but the iPhone has not connected to the receiver. Read the current network and check the firewall or router client isolation settings.'],
    ['连接','連接','Connection'],['显示','顯示','Display'],['音频','音訊','Audio'],['关于','關於','About'],['关于WinPlay','關於WinPlay','About WinPlay'],
    ['折叠侧栏','摺疊側欄','Collapse sidebar'],['调整侧栏宽度','調整側欄寬度','Resize sidebar'],['设置导航','設定導覽','Settings navigation'],
    ['未连接','未連接','Not connected'],['接收中','接收中','Receiving'],['已收到视频','已收到影片','Video received'],['版本','版本','Version'],['接收端','接收端','Receiver'],
    ['状态','狀態','Status'],['准备连接','準備連接','Ready to connect'],['配置无线网络后启动接收。','設定無線網路後啟動接收。','Configure the wireless network, then start receiving.'],
    ['自动（上次连接的iPhone）','自動（上次連接的iPhone）','Automatic (last connected iPhone)'],['刷新iPhone列表','重新整理iPhone列表','Refresh iPhone list'],
    ['自动模式优先使用上次成功显示画面的iPhone。','自動模式優先使用上次成功顯示畫面的iPhone。','Automatic selection prefers the last iPhone that successfully displayed video.'],
    ['应用','應用程式','Application'],['语言','語言','Language'],['跟随系统','跟隨系統','System default'],['关闭主窗口时','關閉主視窗時','When closing the main window'],['每次询问','每次詢問','Ask every time'],
    ['退出WinPlay','結束WinPlay','Quit WinPlay'],['最小化到托盘','最小化至系統匣','Minimize to system tray'],['外观','外觀','Appearance'],['跟随Windows','跟隨Windows','Follow Windows'],['浅色','淺色','Light'],['深色','深色','Dark'],
    ['无线网络','無線網路','Wireless network'],['无线模式','無線模式','Wireless mode'],['本机移动热点','本機行動熱點','Windows mobile hotspot'],['现有局域网','現有區域網路','Existing Wi-Fi network'],
    ['网络名称（SSID）','網路名稱（SSID）','Network name (SSID)'],['网络密码','網路密碼','Network password'],['8—63位','8—63個字元','8–63 characters'],['网络接口','網路介面','Network interface'],['刷新','重新整理','Refresh'],
    ['信道','頻道','Channel'],['接入点BSSID（可选）','存取點BSSID（選填）','Access point BSSID (optional)'],['读取当前网络和密码','讀取目前網路和密碼','Read current network and password'],['正在读取网络和密码…','正在讀取網路和密碼…','Reading network and password…'],
    ['打开移动热点','開啟行動熱點','Open mobile hotspot'],['打开蓝牙设置','開啟藍牙設定','Open Bluetooth settings'],['打开定位设置','開啟定位設定','Open location settings'],
    ['局域网Wi-Fi名称（SSID）','區域網路Wi-Fi名稱（SSID）','Wi-Fi network name (SSID)'],['本机热点名称','本機熱點名稱','Mobile hotspot name'],['局域网Wi-Fi共享密码','區域網路Wi-Fi共用密碼','Wi-Fi shared password'],['本机热点密码','本機熱點密碼','Mobile hotspot password'],
    ['两端共用的Wi-Fi名称','兩端共用的Wi-Fi名稱','Shared Wi-Fi network name'],['Windows移动热点名称','Windows行動熱點名稱','Windows mobile hotspot name'],
    ['Windows与iPhone加入同一Wi-Fi，并完成蓝牙配对。访客网络、客户端隔离和企业认证可能阻止连接。','Windows與iPhone加入同一Wi-Fi，並完成藍牙配對。訪客網路、用戶端隔離和企業驗證可能阻止連接。','Connect Windows and iPhone to the same Wi-Fi and pair them using Bluetooth. Guest networks, client isolation or enterprise authentication may block the connection.'],
    ['在Windows设置中开启移动热点，填写相同的名称、密码和信道，并完成iPhone蓝牙配对。','在Windows設定中開啟行動熱點，填寫相同的名稱、密碼和頻道，並完成iPhone藍牙配對。','Enable mobile hotspot in Windows settings, enter its name, password and channel, and pair the iPhone using Bluetooth.'],
    ['自动检测连接现有Wi-Fi的网卡；两端须可互访。','自動偵測連接現有Wi-Fi的網路卡；兩端須可互相存取。','Automatically detects the adapter connected to Wi-Fi. Both devices must be able to reach each other.'],
    ['自动检测Windows移动热点的共享接口；信道0表示自动。','自動偵測Windows行動熱點的共用介面；頻道0表示自動。','Automatically detects the shared Windows mobile hotspot interface. Channel 0 means automatic.'],
    ['请选择网络接口','請選擇網路介面','Select a network interface'],['自动检测','自動偵測','Auto-detect'],['移动热点','行動熱點','Mobile hotspot'],['局域网','區域網路','LAN'],['已保存设备（暂未检测到）','已儲存裝置（暫未偵測到）','Saved device (currently unavailable)'],
    ['显示器','顯示器','Monitor'],['显示位置','顯示位置','Display on'],['内建显示器','內建顯示器','Built-in monitor'],['外接显示器','外接顯示器','External monitor'],['主显示器','主顯示器','Primary monitor'],['物理像素','實體像素','physical pixels'],['切换显示器后应用并重新连接。','切換顯示器後套用並重新連接。','Apply and reconnect after changing the monitor.'],
    ['视频分辨率','影片解析度','Video resolution'],['分辨率','解析度','Resolution'],['屏幕原生像素','螢幕原生像素','Native screen pixels'],['自定义','自訂','Custom'],['宽度（像素）','寬度（像素）','Width (pixels)'],['高度（像素）','高度（像素）','Height (pixels)'],['请求像素','請求像素','Requested pixels'],
    ['按屏幕物理像素显示。原生像素全屏显示，其他分辨率使用可移动、不可调整大小的固定窗口。','按螢幕實體像素顯示。原生像素全螢幕顯示，其他解析度使用可移動、不可調整大小的固定視窗。','Displayed using physical screen pixels. Native resolution fills the screen; other resolutions use a movable window with a fixed size.'],
    ['流畅度','流暢度','Frame rate'],['最高帧率','最高影格率','Maximum frame rate'],['帧率为请求上限，120fps失败依次回退90、60fps。','影格率為請求上限，120fps失敗依次退回90、60fps。','The frame rate is a requested limit. If 120fps fails, WinPlay retries at 90fps and then 60fps.'],
    ['接收统计','接收統計','Reception statistics'],['请求帧率','請求影格率','Requested'],['本次尝试','本次嘗試','Current attempt'],['收到视频','收到影片','Received video'],['解码输出','解碼輸出','Decoded output'],['等待视频尺寸','等待影片尺寸','Waiting for video dimensions'],
    ['CarPlay的“智能缩放显示”可能改变界面大小，请在iPhone上调整。','CarPlay的「智慧縮放顯示」可能改變介面大小，請在iPhone上調整。','CarPlay’s Smart Display Zoom may change the interface size. Adjust it on the iPhone.'],
    ['CarPlay声音','CarPlay聲音','CarPlay audio'],['播放iPhone音频','播放iPhone音訊','Play iPhone audio'],['媒体音量','媒體音量','Media volume'],['通话音量','通話音量','Call volume'],['输出设备','輸出裝置','Output device'],['输入设备','輸入裝置','Input device'],['系统默认设备','系統預設裝置','System default device'],['音乐传输格式','音樂傳輸格式','Music format'],['等待iPhone协商','等待iPhone協商','Waiting for iPhone negotiation'],['刷新设备','重新整理裝置','Refresh devices'],
    ['音量实时生效。设备切换后应用并重新连接，麦克风使用需要系统授权。','音量即時生效。裝置切換後套用並重新連接，麥克風使用需要系統授權。','Volume changes take effect immediately. Apply and reconnect after changing devices. Microphone access requires system permission.'],
    ['正在播放','正在播放','Now playing'],['专辑封面','專輯封面','Album artwork'],['等待iPhone上报媒体信息','等待iPhone提供媒體資訊','Waiting for media information from iPhone'],['未上报歌名','未提供歌名','No title provided'],['上一首','上一首','Previous'],['下一首','下一首','Next'],['播放/暂停','播放/暫停','Play/pause'],
    ['运行架构','執行架構','Architecture'],['开源许可','開源授權','License'],['项目主页','專案首頁','Project homepage'],['基于AndroidPlay与MacPlay，保留上游版权与许可证声明。','基於AndroidPlay與MacPlay，保留上游版權與授權聲明。','Based on AndroidPlay and MacPlay, with upstream copyright and license notices retained.'],
    ['软件更新','軟體更新','Software updates'],['自动检查更新','自動檢查更新','Check for updates automatically'],['检查更新','檢查更新','Check for updates'],['正在检查更新…','正在檢查更新…','Checking for updates…'],['查看发行说明','查看發行說明','Release notes'],['下载更新','下載更新','Download update'],['尚未检查更新','尚未檢查更新','Updates have not been checked yet'],['当前已是最新版本','目前已是最新版本','You are up to date'],['检查更新失败','檢查更新失敗','Could not check for updates'],['没有适合当前架构的安装包','沒有適合目前架構的安裝程式','No installer is available for this architecture'],['发现新版本','發現新版本','Update available'],['稍后','稍後','Later'],
    ['日志','記錄','Logs'],['打开日志','開啟記錄','Open logs'],['导出日志','匯出記錄','Export logs'],['最近日志','最近記錄','Recent logs'],['暂无日志','暫無記錄','No logs yet'],['日志已导出','記錄已匯出','Logs exported'],
    ['认证文件','驗證檔案','Authentication files'],['文件已就绪，等待iPhone验证','檔案已就緒，等待iPhone驗證','Files ready; awaiting iPhone verification'],['缺少文件','缺少檔案','Files missing'],['导入认证文件','匯入驗證檔案','Import authentication files'],['打开认证目录','開啟驗證目錄','Open authentication folder'],['刷新状态','重新整理狀態','Refresh status'],['安装包内置认证文件，本机导入的配套文件优先使用。','安裝程式內建驗證檔案，本機匯入的配套檔案優先使用。','Authentication files are included in the installer. A matching pair imported on this PC takes priority.'],['认证文件已更新','驗證檔案已更新','Authentication files updated'],['认证材料已用Windows DPAPI保护保存','驗證資料已使用Windows DPAPI保護儲存','Authentication files saved with Windows DPAPI protection'],
    ['停止接收','停止接收','Stop receiving'],['显示画面','顯示畫面','Show video'],['启动接收','啟動接收','Start receiving'],['应用并重新连接','套用並重新連接','Apply and reconnect'],['接收已停止','接收已停止','Receiver stopped'],['可以重新启动接收。','可以重新啟動接收。','You can start receiving again.'],
    ['关闭WinPlay','關閉WinPlay','Close WinPlay'],['关闭主窗口时要执行什么操作？','關閉主視窗時要執行什麼操作？','What should happen when you close the main window?'],['最小化到托盘会保持CarPlay连接；退出会停止接收。','最小化至系統匣會保持CarPlay連接；結束會停止接收。','Minimizing to the system tray keeps CarPlay connected. Quitting stops the receiver.'],['取消','取消','Cancel'],['不再提示','不再提示','Do not ask again'],['断开CarPlay','中斷CarPlay','Disconnect CarPlay'],['您确定要断开与iPhone的连接吗？','您確定要中斷與iPhone的連接嗎？','Are you sure you want to disconnect the iPhone?'],['断开后将关闭CarPlay画面，并停止接收。','中斷後將關閉CarPlay畫面，並停止接收。','Disconnecting closes the CarPlay window and stops the receiver.'],['断开连接','中斷連接','Disconnect'],['显示WinPlay','顯示WinPlay','Show WinPlay'],['显示CarPlay','顯示CarPlay','Show CarPlay'],
    ['选择identity.pk8与certificate.p7b','選擇identity.pk8與certificate.p7b','Select identity.pk8 and certificate.p7b'],['请选择一个identity.pk8和一个certificate.p7b','請選擇一個identity.pk8和一個certificate.p7b','Select one identity.pk8 and one certificate.p7b'],['请先停止接收再导入认证材料','請先停止接收再匯入驗證資料','Stop receiving before importing authentication files'],['已取消导入','已取消匯入','Import canceled'],['已取消导出','已取消匯出','Export canceled'],['认证文件大小不合理','驗證檔案大小不合理','Invalid authentication file size'],['认证导入超时','驗證匯入逾時','Authentication import timed out'],['认证导入进程无法启动','驗證匯入程序無法啟動','Could not start the authentication import process'],
    ['Windows未允许麦克风访问，请检查系统隐私设置','Windows未允許麥克風存取，請檢查系統隱私設定','Windows has not allowed microphone access. Check the system privacy settings.'],['界面初始化失败，请重新打开WinPlay','介面初始化失敗，請重新開啟WinPlay','The interface could not initialize. Reopen WinPlay.'],
    ['已读取当前网络和密码。','已讀取目前網路和密碼。','Read the current network and password.'],['已读取当前网络，未能读取密码；已保留原密码。','已讀取目前網路，無法讀取密碼；已保留原密碼。','Read the current network. The password could not be read; the existing password was kept.'],['未能读取当前网络，请检查网络设置后重试。','無法讀取目前網路，請檢查網路設定後重試。','Could not read the current network. Check network settings and try again.'],['网络设置保存失败，请重试。','網路設定儲存失敗，請重試。','Could not save network settings. Try again.'],
    ['正在等待网络接口就绪','正在等待網路介面就緒','Waiting for the network interface'],['启动接收失败','啟動接收失敗','Could not start receiving'],['缺少认证文件','缺少驗證檔案','Authentication files missing'],['请先在关于页导入认证文件','請先在關於頁匯入驗證檔案','Import authentication files on the About page first'],['接收已结束','接收已結束','Receiving ended'],['接收进程退出，请查看关于页日志','接收程序結束，請查看關於頁記錄','The receiver process exited. Check logs on the About page.'],['接收进程无法启动','接收程序無法啟動','Could not start the receiver process'],
    ['CarPlay会话已建立，等待视频','CarPlay工作階段已建立，等待影片','CarPlay session established; waiting for video'],['已收到视频配置','已收到影片設定','Video configuration received'],['正在接收CarPlay视频','正在接收CarPlay影片','Receiving CarPlay video'],['视频通道正在重新连接','影片通道正在重新連接','Reconnecting the video channel'],['视频通道恢复超时','影片通道恢復逾時','Video recovery timed out'],['iPhone结束连接，未收到视频，请重新启动接收','iPhone結束連接，未收到影片，請重新啟動接收','iPhone disconnected before sending video. Start the receiver again.'],['CarPlay协议错误，请重新启动接收','CarPlay通訊協定錯誤，請重新啟動接收','CarPlay protocol error. Start the receiver again.'],
    ['TCP17000接收端口不可用，请检查端口占用','TCP17000接收連接埠無法使用，請檢查連接埠占用','TCP port 17000 is unavailable. Check whether another application is using it.'],['连接iPhone蓝牙RFCOMM服务','連接iPhone藍牙RFCOMM服務','Connecting to the iPhone Bluetooth RFCOMM service'],['蓝牙桥接启动失败','藍牙橋接啟動失敗','Could not start the Bluetooth bridge'],['蓝牙RFCOMM连接失败','藍牙RFCOMM連接失敗','Bluetooth RFCOMM connection failed'],['CarPlay视频连接超时','CarPlay影片連接逾時','CarPlay video connection timed out'],['请检查当前无线模式的网络接口和防火墙','請檢查目前無線模式的網路介面和防火牆','Check the network interface and firewall for the selected wireless mode'],['已发送CarPlay参数，等待iPhone网络连接','已傳送CarPlay參數，等待iPhone網路連接','CarPlay parameters sent; waiting for the iPhone network connection'],['局域网接收已启动，请确认两端在同一Wi-Fi','區域網路接收已啟動，請確認兩端在同一Wi-Fi','LAN receiver started. Make sure both devices are on the same Wi-Fi.'],['本机热点接收已启动，请让iPhone接入Windows移动热点','本機熱點接收已啟動，請讓iPhone連接Windows行動熱點','Mobile hotspot receiver started. Connect the iPhone to the Windows mobile hotspot.'],['接收进程异常，请重新启动接收','接收程序異常，請重新啟動接收','Receiver process error. Start the receiver again.'],['系统媒体同步失败','系統媒體同步失敗','System media synchronization failed'],['音频处理需要检查','音訊處理需要檢查','Audio processing needs attention'],['画面窗口尺寸设置失败','畫面視窗尺寸設定失敗','Could not set the video window size'],['显示器已断开，请重新选择显示位置','顯示器已中斷，請重新選擇顯示位置','The monitor disconnected. Select another monitor.'],['显示器配置已变化','顯示器設定已變更','Monitor configuration changed'],
    ['无法读取显示器物理像素','無法讀取顯示器實體像素','Could not read the monitor’s physical pixel dimensions'],['Windows显示器枚举失败','Windows顯示器列舉失敗','Windows monitor enumeration failed'],['显示器物理尺寸查询失败','顯示器實體尺寸查詢失敗','Could not query the monitor’s physical dimensions'],
    ['请一次选中配套的identity.pk8与certificate.p7b','請一次選取配套的identity.pk8與certificate.p7b','Select the matching identity.pk8 and certificate.p7b together'],['请选择本机移动热点或现有局域网模式','請選擇本機行動熱點或現有區域網路模式','Select mobile hotspot or existing Wi-Fi mode'],
    ['未找到正式发行版','未找到正式發行版','No official release found'],['请求超时，请稍后重试','請求逾時，請稍後重試','The request timed out. Try again later.'],['发行信息过大，请查看发行说明','發行資訊過大，請查看發行說明','The release information is too large. Open the release notes.'],['无法读取GitHub发行信息，请稍后重试','無法讀取GitHub發行資訊，請稍後重試','Could not read GitHub release information. Try again later.'],['暂无适合当前架构的安装包，请查看发行说明','暫無適合目前架構的安裝程式，請查看發行說明','No installer is available for this architecture. Open the release notes.'],
    ['无法确认Windows移动热点共享接口，请检查系统移动热点设置后重试','無法確認Windows行動熱點共用介面，請檢查系統行動熱點設定後重試','Could not verify the Windows mobile hotspot interface. Check the system hotspot settings and try again.'],['所选网卡不是Windows移动热点的共享接口，请自动检测或重新选择','所選網路卡不是Windows行動熱點的共用介面，請自動偵測或重新選擇','The selected adapter is not the shared mobile hotspot interface. Use auto-detect or select another adapter.'],['Windows移动热点尚未就绪，请开启热点并等待共享接口获得地址','Windows行動熱點尚未就緒，請開啟熱點並等待共用介面取得位址','Windows mobile hotspot is not ready. Enable it and wait for the shared interface to obtain an address.'],['所选网卡不是有效的局域网接口，请选择已连接Wi-Fi或以太网的物理网卡','所選網路卡不是有效的區域網路介面，請選擇已連接Wi-Fi或乙太網路的實體網路卡','Select a physical adapter connected to Wi-Fi or Ethernet. The selected adapter is not a valid LAN interface.'],['所选局域网接口尚未连接或没有可用地址，请检查网络连接','所選區域網路介面尚未連接或沒有可用位址，請檢查網路連線','The selected LAN interface is disconnected or has no usable address. Check the network connection.'],['网络检查已取消','網路檢查已取消','Network check canceled'],
    ['帧率必须为30、60、90或120','影格率必須為30、60、90或120','Frame rate must be 30, 60, 90 or 120'],['请填写不超过所选屏幕物理分辨率的偶数像素尺寸','請填寫不超過所選螢幕實體解析度的偶數像素尺寸','Enter even pixel dimensions within the selected monitor’s physical resolution'],['接入点BSSID格式无效','存取點BSSID格式無效','Invalid access point BSSID'],['请填写当前无线模式的实际Wi-Fi名称，最多32字节','請填寫目前無線模式的實際Wi-Fi名稱，最多32位元組','Enter the Wi-Fi name for the selected wireless mode, up to 32 bytes'],['Wi-Fi共享密码必须为8—63位；本版不支持企业或网页登录凭据','Wi-Fi共用密碼必須為8—63個字元；此版本不支援企業或網頁登入憑證','The Wi-Fi shared password must contain 8–63 characters. Enterprise and web login credentials are not supported.'],['请选择已配对的iPhone','請選擇已配對的iPhone','Select a paired iPhone'],['Wi-Fi信道必须为1—196','Wi-Fi頻道必須為1—196','Wi-Fi channel must be between 1 and 196'],['请先在关于页导入有使用权限的配套认证材料','請先在關於頁匯入有使用權限的配套驗證資料','Import a matching pair of authorized authentication files on the About page first'],['请先导入认证文件','請先匯入驗證檔案','Import authentication files first'],['重新连接已取消','重新連接已取消','Reconnection canceled'],['画面窗口尚未创建','畫面視窗尚未建立','The video window has not been created yet'],['正在准备画面窗口','正在準備畫面視窗','Preparing the video window'],['请使用偶数像素尺寸','請使用偶數像素尺寸','Use even pixel dimensions'],
    ['iPhone已接受配件识别','iPhone已接受配件識別','iPhone accepted accessory identification'],['iPhone拒绝MFi认证材料','iPhone拒絕MFi驗證資料','iPhone rejected the MFi authentication files'],['MFi认证已通过，等待CarPlay请求','MFi驗證已通過，等待CarPlay請求','MFi authentication passed; waiting for a CarPlay request'],['配件识别或认证超时','配件識別或驗證逾時','Accessory identification or authentication timed out'],['iAP2认证或消息处理失败','iAP2驗證或訊息處理失敗','iAP2 authentication or message processing failed'],['iPhone控制服务已回应','iPhone控制服務已回應','iPhone control service responded'],['iPhone控制服务探测失败，请检查热点与防火墙','iPhone控制服務探測失敗，請檢查熱點與防火牆','Could not reach the iPhone control service. Check the hotspot and firewall.'],
    ['当前已从{requested}fps回退至{attempt}fps','目前已從{requested}fps退回至{attempt}fps','Fell back from {requested}fps to {attempt}fps'],['实际解码尺寸：{width}×{height}','實際解碼尺寸：{width}×{height}','Decoded dimensions: {width}×{height}'],['输出设备{number}','輸出裝置{number}','Output device {number}'],['输入设备{number}','輸入裝置{number}','Input device {number}'],['发现新版：{version}','發現新版：{version}','Update available: {version}'],['WinPlay{version}已发布。','WinPlay{version}已發布。','WinPlay {version} is available.'],['{channels}声道','{channels}聲道','{channels} channels'],['自定义像素不得超过所选屏幕的{width}×{height}','自訂像素不得超過所選螢幕的{width}×{height}','Custom dimensions cannot exceed {width}×{height} on the selected monitor'],['iPhone控制服务回应：HTTP {code}','iPhone控制服務回應：HTTP {code}','iPhone control service response: HTTP {code}']
  ];
  const dictionary=new Map(entries.map(row=>[row[0],row]));
  function resolveLanguage(selection,systemLocale){
    if(['zh-Hans','zh-Hant','en'].includes(selection))return selection;
    const locale=String(systemLocale||'en').replace(/_/g,'-').toLowerCase();
    if(locale.startsWith('zh'))return /(?:hant|tw|hk|mo)/.test(locale)?'zh-Hant':'zh-Hans';
    return 'en';
  }
  const templates=entries.filter(row=>row[0].includes('{')).map(row=>{
    const names=[];let source='',last=0;for(const match of row[0].matchAll(/\{(\w+)\}/g)){source+=row[0].slice(last,match.index).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(.+?)';names.push(match[1]);last=match.index+match[0].length}source+=row[0].slice(last).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return {row,names,pattern:new RegExp('^'+source+'$')};
  });
  function translate(text,selection='system',systemLocale='en'){
    if(typeof text!=='string')return text;
    const language=resolveLanguage(selection,systemLocale),column=language==='zh-Hans'?0:language==='zh-Hant'?1:2;
    if(column===0)return text;
    const exact=dictionary.get(text);if(exact)return exact[column];
    for(const template of templates){const match=template.pattern.exec(text);if(match)return template.row[column].replace(/\{(\w+)\}/g,(_,name)=>match[template.names.indexOf(name)+1]);}
    return text;
  }
  return {resolveLanguage,translate};
});
