(function(root){class VideoReceiver{
 constructor(api){this.api=api;this.generation=0;this.pending=[];this.submitted=[];this.awaitKey=true;this.lastRequest=-Infinity;this.lastOutput=0;this.lastInput=0;this.retries=[];this.timer=setInterval(()=>this.tick(),1000)}
 ack(message){this.api.ack?.(message,{decoderQueueSize:this.decoder?.decodeQueueSize||0,ready:!!this.ready,awaitKey:this.awaitKey})}
 releaseAcks(decoder){if(!decoder||decoder!==this.decoder)return;const queued=Number(decoder.decodeQueueSize)||0,consumed=this.submitted.splice(0,Math.max(0,this.submitted.length-queued));for(const frame of consumed)this.ack(frame)}
 request(){const now=Date.now();if(now-this.lastRequest>=900){this.lastRequest=now;this.api.requestKey()}}
 async configure(message,recovery=false){const bytes=new Uint8Array(message.data);if(!bytes.length)return;if(!recovery&&this.description&&bytes.length===this.description.length&&bytes.every((b,i)=>b===this.description[i]))return;
 const generation=++this.generation;this.api.reset?.();this.ready=false;this.awaitKey=true;for(const frame of [...this.pending,...this.submitted])this.ack(frame);this.pending=[];this.submitted=[];if(this.decoder&&this.decoder.state!=='closed')this.decoder.close();this.decoder=undefined;this.description=bytes;if(bytes[0]!==1||bytes.length<7){this.api.fail('收到不支持的H.264视频配置');return}this.lengthSize=(bytes[4]&3)+1;const config={codec:'avc1.'+[bytes[1],bytes[2],bytes[3]].map(n=>n.toString(16).padStart(2,'0')).join(''),description:bytes,optimizeForLatency:true,hardwareAcceleration:this.software?'prefer-software':'prefer-hardware'};
 try{const support=await this.api.Decoder.isConfigSupported(config);if(generation!==this.generation)return;if(!support.supported)throw Error('不支持的视频配置');let decoder;decoder=new this.api.Decoder({output:frame=>{try{if(generation!==this.generation||decoder!==this.decoder)return;this.releaseAcks(decoder);this.lastOutput=Date.now();this.api.output(frame)}finally{frame.close()}},error:e=>{if(generation===this.generation)this.recover(e.message)}});this.decoder=decoder;decoder.addEventListener?.('dequeue',()=>{if(generation===this.generation)this.releaseAcks(decoder)});decoder.configure(config);this.ready=true;this.lastOutput=Date.now();const pending=this.pending;this.pending=[];for(const m of pending)this.decode(m);if(this.awaitKey)this.request()}catch(e){if(generation===this.generation)this.recover(e.message)}}
 key(data){for(let i=0;i+this.lengthSize<=data.length;){let n=0;for(let k=0;k<this.lengthSize;k++)n=n*256+data[i+k];i+=this.lengthSize;if(n<1||i+n>data.length)return false;if((data[i]&31)===5)return true;i+=n}return false}
 decode(m){if(m.reset&&this.description){if(m.resetReason==='decoder-stall'){if(!this.recover('解码队列停滞')){this.ack(m);return}}else this.configure({data:this.description},true);m={...m,reset:false}}this.lastInput=Date.now();const data=new Uint8Array(m.data),key=this.key(data);if(!this.ready){if(key){for(const frame of this.pending)this.ack(frame);this.pending=[]}else if(!this.pending.length){this.ack(m);this.request();return}if(this.pending.length<16)this.pending.push(m);else{for(const frame of [...this.pending,m])this.ack(frame);this.pending=[];this.request()}return}if(this.awaitKey&&!key){this.ack(m);this.request();return}if(this.decoder.decodeQueueSize>24){this.ack(m);this.recover('解码队列积压');return}try{const decoder=this.decoder;this.submitted.push(m);decoder.decode(new this.api.Chunk({type:key?'key':'delta',timestamp:m.timestamp,data}));if(decoder!==this.decoder||!this.ready)return;if(key)this.awaitKey=false;this.releaseAcks(decoder)}catch(e){this.recover(e.message)}}
 recover(reason){const now=Date.now();this.retries=this.retries.filter(t=>now-t<10000);if(this.retries.length>=3){this.ready=false;this.api.fail('视频恢复失败：'+reason);return false}this.retries.push(now);this.software=true;this.api.recover(reason);this.configure({data:this.description},true);return true}
 tick(){if(!this.ready)return;if(this.awaitKey)this.request();else if(this.lastInput>this.lastOutput&&Date.now()-this.lastOutput>2500)this.recover('视频输出停滞')}
 close(){clearInterval(this.timer);this.generation++;this.ready=false;for(const frame of [...this.pending,...this.submitted])this.ack(frame);this.pending=[];this.submitted=[];if(this.decoder&&this.decoder.state!=='closed')this.decoder.close()}
}if(typeof module==='object')module.exports=VideoReceiver;else root.WinPlayVideoReceiver=VideoReceiver})(globalThis);
