// Interface-bound Bonjour publication and iPhone control probing, adapted from
// AndroidPlay CarPlayBonjour.kt and MacPlay livi-runtime/src/bonjour.rs.
import net from 'node:net'
import os from 'node:os'
const mdns:any=require('multicast-dns')
export function connectProbeRequest(host:string,port:number,deviceId:string){const unscoped=host.split('%')[0];if(!net.isIP(unscoped)||port<1||port>65535||!Number.isInteger(port)||!/^[0-9a-f:]+$/i.test(deviceId))throw new Error('CarPlay控制探测参数无效');return `GET /ctrl-int/1/connect HTTP/1.1\r\nHost: ${unscoped.includes(':')?'['+unscoped+']':unscoped}:${port}\r\nUser-Agent: AirPlay/950.7.1\r\nAirPlay-Receiver-Device-ID: ${deviceId.replaceAll(':','')}\r\nConnection: close\r\n\r\n`}
type Record={name:string;type:string;data:any;ttl:number}
export class Discovery {
 private sockets:any[]=[];private connections=new Set<net.Socket>();private records:Record[]=[];private cache=new Map<string,{record:Record;expires:number}>();private attempted=new Set<string>();private timers=new Set<NodeJS.Timeout>();private interval:NodeJS.Timeout;private closed=false
 constructor(private iface:string,private identity:{deviceId:string;pk:string;pi:string;btMac:string},private targetBt:string,private allowed:()=>boolean,private status:(s:string)=>void){
  const addresses=(os.networkInterfaces()[iface]||[]).filter(a=>!a.internal),host='winplay-'+identity.pi.toLowerCase()+'.local',fqdn='WinPlay._airplay._tcp.local'
  const txt={deviceid:identity.deviceId,features:'0x44540380,0x61',flags:'0x4',model:'WinPlay',srcvers:'950.7.1',protovers:'1.1',pi:identity.pi,pk:identity.pk}
  this.records=[{name:'_airplay._tcp.local',type:'PTR',ttl:120,data:fqdn},{name:fqdn,type:'SRV',ttl:120,data:{port:17000,target:host}},{name:fqdn,type:'TXT',ttl:120,data:Object.entries(txt).map(([k,v])=>Buffer.from(k+'='+v))},...addresses.filter(a=>a.family==='IPv4'||a.family==='IPv6'&&a.address.startsWith('fe80:')).map(a=>({name:host,type:a.family==='IPv4'?'A':'AAAA',ttl:120,data:a.address.split('%')[0]}))]
  for(const family of ['IPv4','IPv6']){const a=addresses.find(n=>n.family===family&&(family!=='IPv6'||n.address.startsWith('fe80:')));if(!a)continue;const scope=family==='IPv6'?a.address.split('%')[0]+'%'+(a as any).scopeid:a.address
   try{const socket=mdns({type:family==='IPv6'?'udp6':'udp4',ip:family==='IPv6'?'ff02::fb':'224.0.0.251',interface:scope,bind:family==='IPv6'?'::':a.address,reuseAddr:true});this.sockets.push(socket);socket.on('error',()=>status('Bonjour端口或网络接口不可用，请检查防火墙'));socket.on('warning',()=>{});socket.on('ready',()=>{socket.respond({answers:this.records});socket.query({questions:[{name:'_carplay-ctrl._tcp.local',type:'PTR'}]})});socket.on('query',(q:any)=>{if(q.questions?.some((question:any)=>this.records.some(r=>r.name.toLowerCase()===question.name.toLowerCase())))socket.respond({answers:this.records})});socket.on('response',(p:any)=>this.receive(p,a))}catch{status('所选接口的Bonjour广播无法启动')}
  }
  this.interval=setInterval(()=>{for(const socket of this.sockets){socket.query({questions:[{name:'_carplay-ctrl._tcp.local',type:'PTR'}]})}this.resolve()},1500)
 }
 private receive(packet:any,local:os.NetworkInterfaceInfo){for(const r of [...packet.answers||[],...packet.additionals||[]]){if(!['PTR','SRV','TXT','A','AAAA'].includes(r.type))continue;const key=r.name.toLowerCase()+'|'+r.type;if(r.ttl===0)this.cache.delete(key);else {if(this.cache.size>=128)this.cache.delete(this.cache.keys().next().value!);this.cache.set(key,{record:r,expires:Date.now()+Math.min(600,r.ttl)*1000})}}this.resolve(local)}
 private resolve(local?:os.NetworkInterfaceInfo){if(this.closed||!this.allowed())return;for(const [key,v] of this.cache)if(v.expires<Date.now())this.cache.delete(key)
  for(const v of this.cache.values()){const r=v.record;if(r.type!=='SRV'||!r.name.toLowerCase().endsWith('._carplay-ctrl._tcp.local'))continue;const txt=this.cache.get(r.name.toLowerCase()+'|TXT')?.record.data||[];const id=txt.map((b:Buffer)=>b.toString()).find((s:string)=>s.startsWith('id='))?.slice(3);const normalize=(s:string)=>s.replace(/[^0-9a-f]/gi,'').toLowerCase();if(this.targetBt&&id&&normalize(id)!==normalize(this.targetBt))continue
   const all=(os.networkInterfaces()[this.iface]||[]).filter(a=>!a.internal);const candidates=local?[local]:all;for(const a of candidates){const record=this.cache.get(r.data.target.toLowerCase()+'|'+(a.family==='IPv6'?'AAAA':'A'))?.record;if(!record)continue;const remote=String(record.data),scope=(a as any).scopeid||a.address.split('%')[1];if(a.family==='IPv6'&&!remote.startsWith('fe80:'))continue;const scoped=remote.startsWith('fe80:')?remote+'%'+scope:remote;const source=a.family==='IPv6'?a.address.split('%')[0]+'%'+scope:a.address;const key=scoped+':'+r.data.port;if(this.attempted.has(key))continue;this.attempted.add(key);this.probe(scoped,source,r.data.port,1);break}
  }
 }
 private probe(host:string,localAddress:string,port:number,attempt:number){if(this.closed)return;let request:string;try{request=connectProbeRequest(host,port,this.identity.deviceId)}catch{return}const socket=net.createConnection({host,port,localAddress}),cleanup=()=>this.connections.delete(socket);this.connections.add(socket);let responded=false,first='';socket.setTimeout(5000,()=>socket.destroy());socket.on('connect',()=>socket.write(request));socket.on('error',()=>{});socket.on('data',b=>{first=(first+b.toString('ascii')).slice(0,256);if(first.includes('\r\n')){responded=true;const code=/^HTTP\/\d\.\d (\d{3})/.exec(first)?.[1];this.status(code?'iPhone控制服务回应：HTTP '+code:'iPhone控制服务已回应');socket.destroy()}});socket.on('close',()=>{cleanup();if(!responded&&attempt<7&&!this.closed){const timer=setTimeout(()=>{this.timers.delete(timer);this.probe(host,localAddress,port,attempt+1)},1500);this.timers.add(timer)}else if(!responded&&!this.closed)this.status('iPhone控制服务探测失败，请检查热点与防火墙')})}
 destroy(){if(this.closed)return;this.closed=true;clearInterval(this.interval);for(const timer of this.timers)clearTimeout(timer);for(const connection of this.connections)connection.destroy();for(const socket of this.sockets){try{socket.respond({answers:this.records.map(r=>({...r,ttl:0}))});socket.destroy()}catch{}}this.sockets=[]}
}
