const {app,BrowserWindow,ipcMain,screen,nativeTheme,dialog,shell,safeStorage,session,Tray,Menu}=require('electron');
const {fork,execFile}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const {SystemMedia}=require('./system-media.cjs');
app.commandLine.appendSwitch('disable-features','HardwareMediaKeyHandling,MediaSessionService');
const {resolveConnectionSettings}=require('./connection-settings.cjs');
const {chooseCloseBehavior,validateCloseBehavior}=require('./close-behavior.cjs');
const {physicalDisplay,videoSize,dipVideoBounds}=require('./display-settings.cjs');
const selfTest=process.argv.includes('--self-test');
if(!selfTest&&!app.requestSingleInstanceLock()){app.quit();process.exit(0)}
app.on('second-instance',()=>restoreMain());
app.setName('WinPlay');app.setPath('userData',selfTest?fs.mkdtempSync(path.join(os.tmpdir(),'winplay-test-')):path.join(app.getPath('appData'),'WinPlay'));
const root=path.resolve(__dirname,'..'),uiRoot=path.join(__dirname,'ui');
const resources=app.isPackaged?process.resourcesPath:path.join(root,'resources');
const engineRoot=app.isPackaged?path.join(resources,'app.asar.unpacked'):root;
const validationDir=process.env.WINPLAY_TEST_OUTPUT||path.join(root,'docs/validation');
const native=app.isPackaged?path.join(resources,'native','WinPlay.Platform.exe'):path.join(root,'build/native/WinPlay.Platform.exe');
const runtime=path.join(resources,'node/node.exe'),dataDir=path.join(app.getPath('userData'),'data');
const defaults={resolutionMode:'preset',fullScreen:false,closeBehavior:'ask',wirelessMode:'hotspot',lanSsid:'',lanPassword:'',lanChannel:36,lanNetworkInterface:'',lanAccessPointMac:'',width:1280,height:720,fps:60,theme:'system',displayId:0,audioEnabled:true,mediaVolume:1,callVolume:1,inputDevice:'',outputDevice:'',ssid:'',password:'',channel:36,targetBluetooth:'',lastBluetooth:'',networkInterface:''};
let systemMedia,tray,videoHidden=false;
let videoClosePromptOpen=false,closePromptOpen=false,connectionEpoch=0,reconnecting=false;
let settings={...defaults},main,video,engine,lastConfig,pendingFrames=[],videoReady=false,videoSized=false,videoPixelSize,videoDisplayId,videoSizingTimer,running=false,closing=false;let diagnostics=[],stats={requested:60,attempt:60,receivedFps:0,decodedFps:0};
function save(){fs.mkdirSync(dataDir,{recursive:true});const file=path.join(dataDir,'settings.dpapi');fs.writeFileSync(file+'.new',safeStorage.encryptString(JSON.stringify(settings)));fs.renameSync(file+'.new',file)}
function load(){try{diagnostics=JSON.parse(fs.readFileSync(path.join(dataDir,'diagnostics.json'),'utf8')).slice(-150)}catch{}try{const saved=JSON.parse(safeStorage.decryptString(fs.readFileSync(path.join(dataDir,'settings.dpapi'))));settings={...defaults};for(const key of Object.keys(defaults))if(typeof saved[key]===typeof defaults[key])settings[key]=saved[key];save()}catch{}}
function send(type,payload={}){if(type==='now-playing')systemMedia?.update(payload.state,payload.artChanged);else if(type==='position')systemMedia?.position(payload.positionMs);else if(type==='stopped')systemMedia?.clear();if(main&&!main.isDestroyed())main.webContents.send('event',{type,...payload})}
function log(status,detail=''){diagnostics.push({time:new Date().toISOString(),status,detail});diagnostics=diagnostics.slice(-150);try{fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(path.join(dataDir,'diagnostics.json'),JSON.stringify(diagnostics))}catch{}send(['控制请求','流协商','控制命令','事件通道已连接','建立iAP网络链路','iAP网络数据通道已连接','视频接收端口已就绪','视频TCP通道已连接','音频运行统计'].includes(status)?'diagnostic':'status',{status,detail})}
function restoreMain(){if(!main||main.isDestroyed())return;main.setSkipTaskbar(false);main.restore();main.show();main.focus()}
function hideMain(){if(!main||main.isDestroyed())return;main.setSkipTaskbar(true);main.hide()}
function hideVideo(){if(!video||video.isDestroyed())return;videoHidden=true;video.setSkipTaskbar(true);video.hide()}
function restoreVideo(){if(!video||video.isDestroyed()||!videoSized)return;videoHidden=false;video.setSkipTaskbar(false);video.restore();video.show();video.focus()}
function updateTray(){tray?.setContextMenu(Menu.buildFromTemplate([{label:'打开WinPlay',click:restoreMain},{label:'显示CarPlay画面',enabled:!!video&&!video.isDestroyed(),click:restoreVideo},{type:'separator'},{label:'退出WinPlay',click:()=>app.quit()}]))}
function createTray(){tray=new Tray(path.join(resources,'icons','winplay.ico'));tray.setToolTip('WinPlay');tray.on('click',restoreMain);tray.on('double-click',restoreMain);updateTray()}
function createMain(){main=new BrowserWindow({width:900,height:650,minWidth:900,minHeight:560,show:!selfTest,backgroundColor:nativeTheme.shouldUseDarkColors?'#171717':'#ffffff',title:'WinPlay',autoHideMenuBar:true,icon:path.join(resources,'icons','winplay-256.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});main.loadFile(path.join(uiRoot,'index.html'));main.on('close',async event=>{if(closing)return;event.preventDefault();if(closePromptOpen)return;closePromptOpen=true;try{const choice=await chooseCloseBehavior(settings.closeBehavior,()=>dialog.showMessageBox(main,{type:'question',title:'关闭WinPlay',message:'关闭主窗口时要执行什么操作？',detail:'最小化到托盘会保持CarPlay连接；退出会停止接收。',buttons:['退出WinPlay','最小化到托盘','取消'],defaultId:1,cancelId:2,checkboxLabel:'不再提示',checkboxChecked:false,noLink:true}));if(choice.remember){settings.closeBehavior=choice.remember;save();send('close-behavior',{value:choice.remember})}if(choice.action==='minimize')hideMain();else if(choice.action==='exit')app.quit()}finally{closePromptOpen=false}});main.webContents.setWindowOpenHandler(()=>({action:'deny'}));main.webContents.on('will-navigate',e=>e.preventDefault())}
function selectedDisplay(config=settings){return screen.getAllDisplays().find(d=>d.id===config.displayId)||screen.getPrimaryDisplay()}
function displayPixels(display){return physicalDisplay(display,rect=>screen.dipToScreenRect(null,rect))}
function setVideoPixels(){if(!video||video.isDestroyed()||!videoPixelSize)return;const current=video;current.setResizable(true);const handle=current.getNativeWindowHandle().readBigUInt64LE().toString();execFile(native,['window-pixels',handle,String(videoPixelSize.width),String(videoPixelSize.height)],{windowsHide:true,timeout:5000},(error,out)=>{if(video!==current||current.isDestroyed())return;if(error){log('画面窗口尺寸设置失败',error.message);stop();return}try{const actual=JSON.parse(out);if(actual.clientWidth!==videoPixelSize.width||actual.clientHeight!==videoPixelSize.height)throw Error('物理像素尺寸不一致');current.setResizable(false);current.webContents.send('event',{type:'video-viewport',width:videoPixelSize.width,height:videoPixelSize.height});videoSized=true;if(!selfTest&&!videoHidden){current.show();current.focus()}}catch(e){log('画面窗口尺寸设置失败',e.message);stop()}})}
function createVideo(config=settings){if(video&&!video.isDestroyed())return;const target=selectedDisplay(config),size=videoSize(config,displayPixels(target)),bounds=dipVideoBounds(target,size);videoPixelSize=size;videoDisplayId=target.id;videoReady=false;videoSized=false;videoHidden=false;
 video=new BrowserWindow({...bounds,resizable:false,maximizable:false,fullscreenable:false,frame:!size.fullScreen,thickFrame:false,roundedCorners:false,title:'WinPlay · CarPlay',icon:path.join(resources,'icons','winplay-256.png'),show:false,backgroundColor:'#000000',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
 updateTray();video.on('minimize',event=>{event.preventDefault();hideVideo()});video.setMenu(null);video.webContents.setVisualZoomLevelLimits(1,1);video.webContents.on('before-input-event',(event,input)=>{if(input.type==='keyDown'&&input.key==='Escape'){event.preventDefault();hideVideo()}if((input.control||input.meta)&&['+','-','=','0'].includes(input.key))event.preventDefault()});video.on('will-resize',event=>event.preventDefault());setVideoPixels();
 video.on('close',async event=>{if(closing||!(running||reconnecting))return;event.preventDefault();if(videoClosePromptOpen)return;videoClosePromptOpen=true;const current=video,epoch=connectionEpoch;try{const choice=await dialog.showMessageBox(current,{type:'question',title:'断开CarPlay',message:'您确定要断开与iPhone的连接吗？',detail:'断开后将关闭CarPlay画面，并停止接收。',buttons:['断开连接','取消'],defaultId:1,cancelId:1,noLink:true});if(choice.response===0&&video===current&&!current.isDestroyed()&&connectionEpoch===epoch)stop()}catch(e){if(video===current&&!current.isDestroyed())log('断开确认无法显示',e.message)}finally{videoClosePromptOpen=false}});
 video.loadFile(path.join(uiRoot,'video.html'));video.on('closed',()=>{video=undefined;videoReady=false;videoSized=false;updateTray();if((running||reconnecting)&&!closing)stop()});video.webContents.setWindowOpenHandler(()=>({action:'deny'}));video.webContents.on('will-navigate',e=>e.preventDefault());
 video.webContents.on('did-finish-load',()=>{videoReady=true;video.webContents.setZoomFactor(1);video.webContents.send('event',{type:'video-viewport',width:videoPixelSize.width,height:videoPixelSize.height,fullScreen:videoPixelSize.fullScreen});if(lastConfig)video.webContents.send('event',lastConfig);for(const frame of pendingFrames)video.webContents.send('event',frame);pendingFrames=[]})
}
function closeVideo(){videoReady=false;pendingFrames=[];lastConfig=undefined;if(video&&!video.isDestroyed()){const win=video;video=undefined;win.destroy()}updateTray()}
function worker(){return fork(path.join(engineRoot,'build/engine/run.js'),[],{execPath:runtime,execArgv:[],windowsHide:true,stdio:['ignore','ignore','ignore','ipc'],serialization:'advanced',env:{...process.env,WINPLAY_DATA:dataDir,WINPLAY_NATIVE:native,WINPLAY_RESOURCES:resources}})}
function command(message){if(engine?.connected)engine.send(message)}
function stopped(){running=false;closeVideo();stats={...stats,receivedFps:0,decodedFps:0,decodedWidth:0,decodedHeight:0};send('stopped');send('metrics',stats)}
function stop(){connectionEpoch++;reconnecting=false;if(engine){const previous=engine;engine=undefined;if(previous.connected)previous.send({command:'stop'});setTimeout(()=>previous.kill(),1500).unref()}stopped()}
function handleEngineMessage(msg){
 if(msg.type==='status')log(msg.status,msg.detail)
 else if(msg.type==='video-config'){lastConfig=msg;if(videoReady)video.webContents.send('event',msg)}
 else if(msg.type==='video-frame'){createVideo();if(videoReady)video.webContents.send('event',msg);else if(pendingFrames.length<16)pendingFrames.push(msg);else command({command:'video-ack'})}
 else if(msg.type==='connected'){settings.lastBluetooth=engine?.selectedPhone||settings.targetBluetooth||settings.lastBluetooth;save();send(msg.type,msg)}
 else if(msg.type==='metrics'){stats={...stats,...msg};send('metrics',stats)}
 else if(msg.type==='stopped'){stopped()}
 else if(msg.type==='show-settings')restoreMain()
 else send(msg.type,msg)
}
function start(config={...settings}){if(running)return;const target=selectedDisplay(config),size=videoSize(config,displayPixels(target));const resolved={...resolveConnectionSettings(config),width:size.width,height:size.height};if(!resolved.targetBluetooth)resolved.targetBluetooth=settings.lastBluetooth;validateSettings(resolved);running=true;send('starting');try{createVideo(config)}catch(e){stopped();throw e}const proc=worker();engine=proc;proc.selectedPhone=resolved.targetBluetooth;proc.on('message',msg=>{if(engine===proc)handleEngineMessage(msg)});proc.on('exit',code=>{if(engine!==proc)return;engine=undefined;if(running)log('接收已结束',code&&code!==0?'接收进程退出，请查看诊断页':'');stopped()});proc.on('error',()=>{log('接收进程无法启动');stop()});proc.send({command:'start',settings:resolved})}
function validateSettings(s){if(![30,60,90,120].includes(s.fps))throw new Error('帧率必须为30、60、90或120');if(!Number.isInteger(s.width)||!Number.isInteger(s.height)||s.width<320||s.height<200||s.width%2||s.height%2)throw new Error('请填写不超过所选屏幕物理分辨率的偶数像素尺寸');if(s.wirelessMode==='lan'&&s.accessPointMac&&!/^[\da-f]{2}(:[\da-f]{2}){5}$/i.test(s.accessPointMac.trim()))throw new Error('接入点 BSSID 格式无效');if(!s.ssid.trim()||Buffer.byteLength(s.ssid)>32||s.ssid.includes('\0'))throw new Error('请填写当前无线模式的实际 Wi-Fi 名称，最多32字节');if(s.password.length<8||s.password.length>63||s.password.includes('\0'))throw new Error('Wi-Fi共享密码必须为8—63位；本版不支持企业或网页登录凭据');if(!/^[\da-f]{2}(:[\da-f]{2}){5}$/i.test(s.targetBluetooth))throw new Error('请选择已配对的iPhone');if(!Number.isInteger(s.channel)||s.channel<1||s.channel>196)throw new Error('Wi-Fi信道必须为1—196');if(!s.networkInterface)throw new Error('请选择承载CarPlay的网络接口')}
function checkSender(event){const windows=[main,video].filter(Boolean);if(!windows.some(w=>!w.isDestroyed()&&w.webContents.id===event.sender.id))throw new Error('IPC来源无效')}
function authExists(){return ['identity.pk8.dpapi','certificate.p7b.dpapi'].every(n=>fs.existsSync(path.join(dataDir,'authentication',n)))||['identity.pk8','certificate.p7b'].every(n=>fs.existsSync(path.join(resources,'authentication',n)))}
ipcMain.handle('call',async(event,op,arg)=>{checkSender(event);try{switch(op){
 case 'state':return {ok:true,settings,version:app.getVersion(),running,dark:nativeTheme.shouldUseDarkColors,auth:authExists(),stats,diagnostics};
 case 'save':{if(Object.hasOwn(arg,'closeBehavior'))validateCloseBehavior(arg.closeBehavior);const allowed=Object.keys(defaults);const next={...settings};for(const key of allowed)if(Object.hasOwn(arg,key)&&typeof arg[key]===typeof defaults[key])next[key]=arg[key];if(!['system','light','dark'].includes(next.theme))throw new Error('主题无效');next.mediaVolume=Math.max(0,Math.min(1,next.mediaVolume));next.callVolume=Math.max(0,Math.min(1,next.callVolume));if(!['hotspot','lan'].includes(next.wirelessMode))throw new Error('无线模式无效');videoSize(next,displayPixels(screen.getAllDisplays().find(d=>d.id===next.displayId)||screen.getPrimaryDisplay()));settings=next;save();nativeTheme.themeSource=settings.theme;send('appearance',{dark:nativeTheme.shouldUseDarkColors});command({command:'audio',mediaVolume:settings.mediaVolume,callVolume:settings.callVolume});send('audio-enabled',{enabled:settings.audioEnabled});if(!running)send('audio-devices',{inputDevice:settings.inputDevice,outputDevice:settings.outputDevice});return {ok:true};}
 case 'start':if(!authExists())throw new Error('请先在诊断页导入有使用权限的配套认证材料');start();return {ok:true};
 case 'restart':{if(!authExists())throw Error('请先导入认证文件');const target=selectedDisplay(),size=videoSize(settings,displayPixels(target));validateSettings({...resolveConnectionSettings(settings),width:size.width,height:size.height,targetBluetooth:settings.targetBluetooth||settings.lastBluetooth});const snapshot={...settings},previous=engine;stop();const ticket=connectionEpoch;reconnecting=true;try{createVideo(snapshot)}catch(e){reconnecting=false;closeVideo();throw e}if(previous)await new Promise(resolve=>{const timer=setTimeout(()=>{previous.kill();resolve()},2200);previous.once('exit',()=>{clearTimeout(timer);resolve()})});if(connectionEpoch!==ticket)return {ok:false,error:'重新连接已取消'};reconnecting=false;start(snapshot);return {ok:true};}
 case 'show-video':if(!video||video.isDestroyed())throw Error('画面窗口尚未创建');if(!videoSized)throw Error('正在准备画面窗口');restoreVideo();return {ok:true};
 case 'open-auth':{const dir=path.join(dataDir,'authentication');fs.mkdirSync(dir,{recursive:true});const error=await shell.openPath(dir);if(error)throw Error(error);return {ok:true};}
 case 'open-log':{const file=path.join(dataDir,'diagnostics.json');if(!fs.existsSync(file))fs.writeFileSync(file,'[]');const error=await shell.openPath(file);if(error)throw Error(error);return {ok:true};}
 case 'settings-location':await shell.openExternal('ms-settings:privacy-location');return {ok:true};
 case 'read-network':case 'read-password':{if(op==='read-password'&&(!arg?.ssid||arg.ssid.length>32||arg.ssid.includes('\0')))throw Error('请先填写SSID');const args=op==='read-network'?['wlan','show','interfaces']:['wlan','show','profile','name='+arg.ssid,'key=clear'];return await new Promise(resolve=>execFile('netsh.exe',args,{windowsHide:true,timeout:10000,encoding:'buffer'},(error,out)=>{if(error)return resolve({ok:false,error:'无法读取无线网络，请检查Wi-Fi与Windows权限'});const text=new TextDecoder('gb18030').decode(out);const pick=names=>text.match(new RegExp('^\\s*(?:'+names+')\\s*:\\s*(.*?)\\r?$','mi'))?.[1]?.trim();if(op==='read-password'){const password=pick('Key Content|关键内容');resolve(password?{ok:true,password}:{ok:false,error:'该SSID没有可读取的已保存共享密码，请手动填写'})}else{const ssid=pick('SSID'),channel=Number(pick('Channel|频道|信道'));resolve(ssid?{ok:true,ssid,channel,bssid:pick('BSSID')}:{ok:false,error:'未检测到已连接的Wi-Fi；移动热点请在Windows设置中查看'})}}));}
 case 'stop':stop();log('接收已停止');return {ok:true};
 case 'displays':return {ok:true,items:screen.getAllDisplays().map(d=>{const p=displayPixels(d);return {id:d.id,label:d.label||`显示器 ${d.id}`,width:p.width,height:p.height,scaleFactor:d.scaleFactor,internal:d.internal,refreshRate:d.displayFrequency,primary:d.id===screen.getPrimaryDisplay().id}})};
 case 'networks':return await require('./network-selection.cjs').listNetworks();
 case 'bluetooth':return await new Promise(resolve=>execFile(native,['list'],{windowsHide:true,timeout:15000},(error,out,err)=>{if(error)return resolve({ok:false,error:err||'蓝牙设备枚举失败'});try{resolve({ok:true,...JSON.parse(out)})}catch{resolve({ok:false,error:'蓝牙枚举响应无效'})}}));
 case 'settings-hotspot':await shell.openExternal('ms-settings:network-mobilehotspot');return {ok:true};
 case 'settings-bluetooth':await shell.openExternal('ms-settings:bluetooth');return {ok:true};
 case 'import-auth':{if(running)throw new Error('请先停止接收再导入认证材料');const key=await dialog.showOpenDialog(main,{title:'选择有使用权限的 identity.pk8',filters:[{name:'PKCS#8 DER私钥',extensions:['pk8']}],properties:['openFile']});if(key.canceled)return {ok:false,error:'已取消导入'};const cert=await dialog.showOpenDialog(main,{title:'选择与私钥匹配的 certificate.p7b',filters:[{name:'P7B证书链',extensions:['p7b']}],properties:['openFile']});if(cert.canceled)return {ok:false,error:'已取消导入'};const keyBytes=fs.readFileSync(key.filePaths[0]),certBytes=fs.readFileSync(cert.filePaths[0]);if(keyBytes.length>16384||certBytes.length>1024*1024)throw new Error('认证文件大小不合理');return await new Promise(resolve=>{const p=worker();const timer=setTimeout(()=>{p.kill();resolve({ok:false,error:'认证导入超时'})},15000);p.on('message',m=>{if(m.type==='auth-imported'){clearTimeout(timer);resolve({ok:true})}if(m.type==='status'){clearTimeout(timer);resolve({ok:false,error:m.status})}});p.on('error',()=>{clearTimeout(timer);resolve({ok:false,error:'认证导入进程无法启动'})});p.send({command:'import-auth',key:keyBytes,cert:certBytes})});}
 case 'export-diagnostics':{const destination=await dialog.showSaveDialog(main,{defaultPath:'WinPlay-diagnostics.json',filters:[{name:'JSON',extensions:['json']}]});if(destination.canceled)return {ok:false,error:'已取消导出'};fs.writeFileSync(destination.filePath,JSON.stringify({version:app.getVersion(),platform:process.platform,metrics:stats,authenticationImported:authExists(),messages:diagnostics},null,2));return {ok:true};}
 default:throw new Error('未知操作');}}catch(e){return {ok:false,error:e.message}}});
const testInputs=[];
ipcMain.on('input',(event,msg)=>{checkSender(event);if(selfTest&&msg.command==='touch')testInputs.push(msg);const allowed=['touch','media','seek','mic','video-ack','request-keyframe'];if(allowed.includes(msg.command))command(msg);if(msg.command==='decoded'){stats.decodedFps=msg.fps;stats.decodedWidth=msg.width;stats.decodedHeight=msg.height;send('metrics',stats)}if(msg.command==='video-visible'&&video&&!video.isDestroyed()&&!selfTest&&videoSized&&!videoHidden)video.show();if(msg.command==='video-minimize'&&video&&!video.isDestroyed())hideVideo();if(msg.command==='video-close'&&video&&!video.isDestroyed())video.close();if(msg.command==='video-recovery')log('视频解码恢复',String(msg.reason).slice(0,200));if(msg.command==='decode-error'){log('视频解码失败',msg.reason);stop()}if(msg.command==='audio-diagnostic')log('音频运行统计',String(msg.reason).slice(0,400));if(msg.command==='audio-error')log('音频处理需要检查',String(msg.reason).slice(0,200))});
app.on('before-quit',()=>{closing=true;systemMedia?.close();tray?.destroy();tray=undefined;stop()});
app.whenReady().then(()=>{fs.mkdirSync(dataDir,{recursive:true});load();nativeTheme.themeSource=settings.theme;session.defaultSession.setPermissionRequestHandler((wc,permission,cb)=>cb(wc.id===main?.webContents.id&&permission==='media'));session.defaultSession.setPermissionCheckHandler((wc,permission)=>wc?.id===main?.webContents.id&&permission==='media');nativeTheme.on('updated',()=>send('appearance',{dark:nativeTheme.shouldUseDarkColors}));screen.on('display-metrics-changed',()=>{if(video&&!video.isDestroyed()){clearTimeout(videoSizingTimer);videoSizingTimer=setTimeout(()=>{try{const target=screen.getAllDisplays().find(d=>d.id===videoDisplayId);if(!target)throw Error('显示器已断开');videoSize({...videoPixelSize,fullScreen:false},displayPixels(target));video.setBounds(dipVideoBounds(target,videoPixelSize));setVideoPixels()}catch(e){log('显示器配置已变化',e.message);stop()}},200)}});screen.on('display-removed',()=>{if(video&&!video.isDestroyed()&&!screen.getAllDisplays().some(d=>d.id===videoDisplayId)){log('显示器已断开，请重新选择显示位置');stop()}});createMain();createTray();systemMedia=new SystemMedia(path.join(app.isPackaged?path.join(resources,'native'):path.join(root,'build/native'),'WinPlay.Media.exe'),m=>{if(['media','seek'].includes(m.command))command(m)},reason=>log('系统媒体同步失败',reason));if(selfTest)main.webContents.once('did-finish-load',()=>runSelfTest().catch(e=>{fs.mkdirSync(validationDir,{recursive:true});fs.writeFileSync(path.join(validationDir,'electron-failure.txt'),e.stack);app.exit(1)}))});
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function runSelfTest(){main.showInactive();await delay(700);const dir=validationDir;fs.mkdirSync(dir,{recursive:true});const result={date:'2026-10-02',kind:'synthetic Windows Electron test',electron:process.versions.electron,packaged:app.isPackaged,parentExecArgv:process.execArgv,checks:[]};const check=(name,passed,detail='')=>{result.checks.push({name,passed,detail});fs.writeFileSync(path.join(dir,'electron-smoke.json'),JSON.stringify(result,null,2));if(!passed)throw new Error(name+' failed: '+detail)};
 check('first launch defaults to 60fps; experimental PCM control removed',settings.fps===60&&await main.webContents.executeJavaScript(`document.getElementById('fps').value==='60'&&!document.getElementById('mediaCodec')`));
 main.show();main.minimize();await delay(150);check('main minimize button keeps normal taskbar window',main.isMinimized());hideMain();check('main minimizes to tray',!!tray&&!main.isVisible());restoreMain();check('tray restores main',main.isVisible());
 await main.webContents.executeJavaScript(`document.getElementById('wirelessMode').value='lan';document.getElementById('wirelessMode').dispatchEvent(new Event('change'))`);await delay(120);check('wireless-only connection UI and settings',await main.webContents.executeJavaScript(`document.getElementById('wirelessMode').options.length===2&&!document.getElementById('wireless-fields').hidden&&document.querySelectorAll('.nav').length===4`));check('LAN mode selects router settings and location action',await main.webContents.executeJavaScript(`!document.getElementById('lan-bssid').hidden&&document.getElementById('hotspot-settings').textContent==='打开定位设置'&&document.getElementById('ssid-label').textContent.includes('局域网')`));await main.webContents.executeJavaScript(`document.getElementById('wirelessMode').value='hotspot';document.getElementById('wirelessMode').dispatchEvent(new Event('change'))`);await delay(120);check('hotspot mode selects local AP settings',await main.webContents.executeJavaScript(`document.getElementById('lan-bssid').hidden&&document.getElementById('hotspot-settings').textContent==='打开移动热点'&&document.getElementById('ssid-label').textContent.includes('热点')`));
 check('four settings pages',await main.webContents.executeJavaScript(`document.querySelectorAll('.page').length===4 && document.querySelectorAll('.nav').length===4`));
 const themeColors=[];for(const dark of [false,true]){await main.webContents.executeJavaScript(`document.body.classList.toggle('dark',${dark})`);await delay(200);themeColors.push(await main.webContents.executeJavaScript(`getComputedStyle(document.body).backgroundColor`));fs.writeFileSync(path.join(dir,`settings-${dark?'dark':'light'}.png`),(await main.webContents.capturePage()).toPNG())}check('light and dark settings appearances differ',themeColors[0]!==themeColors[1],JSON.stringify(themeColors));
 main.setSize(820,700);await delay(150);check('narrow layout does not horizontally overflow',await main.webContents.executeJavaScript(`document.documentElement.scrollWidth<=window.innerWidth`));fs.writeFileSync(path.join(dir,'settings-narrow.png'),(await main.webContents.capturePage()).toPNG());main.setSize(1050,780);
 const fixture=await main.webContents.executeJavaScript(`(async()=>{const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=720;const c=canvas.getContext('2d');const colors=['#fafafa','#c8ed71','#56d5b4','#4099dc','#925dd5','#e26782'];colors.forEach((color,i)=>{c.fillStyle=color;c.fillRect(i*canvas.width/6,0,canvas.width/6,canvas.height)});c.fillStyle='#171717';c.fillRect(80,230,790,220);c.fillStyle='#fff';c.font='bold 58px Segoe UI';c.fillText('WinPlay 1.1.0',120,320);c.font='26px Segoe UI';c.fillText('Synthetic encrypted video · 1280 × 720',120,375);const frames=[];let config;const encoder=new VideoEncoder({output(chunk,meta){const b=new Uint8Array(chunk.byteLength);chunk.copyTo(b);frames.push(b);if(meta.decoderConfig?.description)config=new Uint8Array(meta.decoderConfig.description)},error(e){throw e}});encoder.configure({codec:'avc1.42001f',width:1280,height:720,bitrate:2000000,framerate:30,avc:{format:'avc'},hardwareAcceleration:'prefer-software'});for(let i=0;i<5;i++){const frame=new VideoFrame(canvas,{timestamp:i*33333});encoder.encode(frame,{keyFrame:true});frame.close()}await encoder.flush();encoder.close();return {config,frames}})()`);
 check('H264 encoder fixture generated',fixture.config?.length>0&&fixture.frames.length===5);
 running=true;send('starting');engine=fork(path.join(engineRoot,'build/engine/selfTest.js'),[],{execPath:runtime,execArgv:[],windowsHide:true,stdio:['ignore','ignore','pipe','ipc'],serialization:'advanced'});engine.stderr.on('data',b=>{result.workerError=String(b).slice(-2000)});engine.on('message',handleEngineMessage);engine.send({command:'fixture',...fixture});for(let i=0;i<40&&(!video||!stats.decodedFps);i++)await delay(200);
 check('encrypted TCP video decoded into dedicated window',!!video&&stats.decodedWidth===1280&&stats.decodedHeight===720&&stats.decodedFps>0,JSON.stringify(stats));hideVideo();check('CarPlay hides to tray',!video.isVisible()&&running);restoreVideo();check('tray restores CarPlay',video.isVisible());video.showInactive();await delay(150);fs.writeFileSync(path.join(dir,'synthetic-video.png'),(await video.webContents.capturePage()).toPNG());
 const resizedFixture=await main.webContents.executeJavaScript(`(async()=>{const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;const c=canvas.getContext('2d');const colors=['#fafafa','#c8ed71','#56d5b4','#4099dc','#925dd5','#e26782'];colors.forEach((color,i)=>{c.fillStyle=color;c.fillRect(i*canvas.width/6,0,canvas.width/6,canvas.height)});c.fillStyle='#171717';c.fillRect(80,230,790,220);c.fillStyle='#fff';c.font='bold 58px Segoe UI';c.fillText('WinPlay 1.1.0',120,320);c.font='26px Segoe UI';c.fillText('Synthetic encrypted video · 960 × 540',120,375);const frames=[];let config;const encoder=new VideoEncoder({output(chunk,meta){const b=new Uint8Array(chunk.byteLength);chunk.copyTo(b);frames.push(b);if(meta.decoderConfig?.description)config=new Uint8Array(meta.decoderConfig.description)},error(e){throw e}});encoder.configure({codec:'avc1.42001f',width:960,height:540,bitrate:2000000,framerate:30,avc:{format:'avc'},hardwareAcceleration:'prefer-software'});for(let i=0;i<5;i++){const frame=new VideoFrame(canvas,{timestamp:i*33333});encoder.encode(frame,{keyFrame:true});frame.close()}await encoder.flush();encoder.close();return {config,frames}})()`);
 engine.send({command:'reconfigure',...resizedFixture});for(let i=0;i<30&&stats.decodedWidth!==960;i++)await delay(200);check('smart scaling resolution change resumes decoded video',stats.decodedWidth===960&&stats.decodedHeight===540,JSON.stringify(stats));engine.send({command:'reconfigure',...fixture});for(let i=0;i<30&&stats.decodedWidth!==1280;i++)await delay(200);check('resolution switches back without reconnecting',stats.decodedWidth===1280&&stats.decodedHeight===720);
 const originalDialog=dialog.showMessageBox;let promptCount=0;try{dialog.showMessageBox=async(_parent,options)=>{promptCount++;check('CarPlay close asks to disconnect',options.message==='您确定要断开与iPhone的连接吗？'&&options.cancelId===1);return {response:1}};video.close();await delay(100);check('cancel close keeps video and reception',!!video&&running);dialog.showMessageBox=originalDialog}finally{dialog.showMessageBox=originalDialog}
 video.webContents.sendInputEvent({type:'mouseDown',x:350,y:300,button:'left',clickCount:1});video.webContents.sendInputEvent({type:'mouseMove',x:420,y:330,button:'left'});video.webContents.sendInputEvent({type:'mouseUp',x:420,y:330,button:'left',clickCount:1});video.webContents.sendInputEvent({type:'mouseWheel',x:500,y:350,deltaY:90,deltaX:0,canScroll:true});await delay(300);
 check('mouse drag and wheel produce bounded HID touch coordinates',testInputs.length>=4&&testInputs.some(t=>t.down)&&testInputs.some(t=>!t.down)&&testInputs.every(t=>t.x>=0&&t.x<=1&&t.y>=0&&t.y<=1),`${testInputs.length} touch events`);
 const mediaApi=await main.webContents.executeJavaScript(`(async()=>{try{return {mediaSession:'mediaSession' in navigator,audioDecoder:typeof AudioDecoder,opusEncoder:(await AudioEncoder.isConfigSupported({codec:'opus',sampleRate:48000,numberOfChannels:1,bitrate:48000})).supported}}catch(e){return {error:e.message}}})()`);check('Windows Chromium media interfaces available',mediaApi.mediaSession&&mediaApi.audioDecoder==='function'&&mediaApi.opusEncoder,JSON.stringify(mediaApi));
 const codecRates=await main.webContents.executeJavaScript(`(async()=>{const result={};for(const sampleRate of [16000,24000,48000]){try{result[sampleRate]=(await AudioEncoder.isConfigSupported({codec:'opus',sampleRate,numberOfChannels:1,bitrate:48000,opus:{frameDuration:20000}})).supported}catch(e){result[sampleRate]=e.message}}return result})()`);check('Opus uplink negotiated sample rates',Object.values(codecRates).every(v=>v===true),JSON.stringify(codecRates));
 send('now-playing',{state:{title:'合成测试曲目',artist:'WinPlay test',album:'Public fixture',trackId:'1',durationMs:120000,positionMs:1000,playing:true,canSeek:true,generation:0,artwork:new Uint8Array([137,80,78,71,13,10,26,10,0])},artChanged:true});await delay(80);
 const coverBefore=await main.webContents.executeJavaScript(`navigator.mediaSession.metadata.artwork[0]?.src`);send('now-playing',{state:{title:'歌名字段中的歌词',artist:'WinPlay test',album:'Public fixture',trackId:'1',durationMs:120000,positionMs:2000,playing:true,canSeek:true,generation:0},artChanged:false});await delay(80);
 check('MediaSession lyrics keep artwork URL and seek state',await main.webContents.executeJavaScript(`navigator.mediaSession.metadata.title==='歌名字段中的歌词'&&navigator.mediaSession.metadata.artwork[0]?.src===${JSON.stringify(coverBefore)}&&!document.getElementById('seek').disabled`));
 await main.webContents.executeJavaScript(`winplayAudio.prepare({inputDevice:'',outputDevice:''})`);send('audio-config',{id:999,opts:{codec:'pcm',clockRate:48000,channels:2,latencyMs:60,realtime:true}});await delay(50);send('audio-active',{id:999,active:true});send('audio-volume',{id:999,level:.5});send('audio',{id:999,sample:0,sequence:1,data:new Uint8Array(3840)});await delay(100);check('Windows audio endpoint stream created',await main.webContents.executeJavaScript(`winplayAudio.outputState().direct&&winplayAudio.outputState().state==='running'&&winplayAudio.outputState().sampleRate===48000`));send('audio-close',{id:999});
 engine.send({command:'stop'});await delay(500);check('passive disconnect closes video and restores start button',!video&&!running&&await main.webContents.executeJavaScript(`document.getElementById('start').textContent==='启动接收'`));
 check('disconnect clears system media metadata',await main.webContents.executeJavaScript(`navigator.mediaSession.metadata===null&&navigator.mediaSession.playbackState==='none'`));
 running=true;send('starting');createVideo();try{dialog.showMessageBox=async()=>({response:0});video.close();await delay(150);check('confirm close stops reception and closes video',!video&&!running&&await main.webContents.executeJavaScript(`document.getElementById('start').textContent==='启动接收'`))}finally{dialog.showMessageBox=originalDialog}
 fs.writeFileSync(path.join(dir,'electron-smoke.json'),JSON.stringify(result,null,2));if(fs.existsSync(path.join(dir,'electron-failure.txt')))fs.unlinkSync(path.join(dir,'electron-failure.txt'));stop();app.exit(0);
}
app.on('window-all-closed',()=>app.quit());app.on('before-quit',stop);
