const {app,BrowserWindow,ipcMain,screen,nativeTheme,dialog,shell,safeStorage,session,Tray,Menu}=require('electron');
const {fork,execFile}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const {SystemMedia}=require('./system-media.cjs');
const I18n=require('./ui/i18n.js');
const {Updates}=require('./updates.cjs');
const {redactText,redactDiagnostics}=require('./diagnostic-redactor.cjs');
const {readCurrentNetwork}=require('./wlan-reader.cjs');
app.commandLine.appendSwitch('disable-features','HardwareMediaKeyHandling,MediaSessionService');
const {resolveConnectionSettings,refreshLanParameters}=require('./connection-settings.cjs');
const {chooseCloseBehavior,validateCloseBehavior}=require('./close-behavior.cjs');
const {physicalDisplay,videoSize,dipVideoBounds}=require('./display-settings.cjs');
const windowSelfTest=process.argv.includes('--window-self-test'),selfTest=windowSelfTest||process.argv.includes('--self-test');
if(!selfTest&&!app.requestSingleInstanceLock()){app.quit();process.exit(0)}
app.on('second-instance',()=>restoreMain());
app.setName('WinPlay');app.setAppUserModelId('io.github.roylyl.winplay');app.setPath('userData',selfTest?fs.mkdtempSync(path.join(os.tmpdir(),'winplay-test-')):path.join(app.getPath('appData'),'WinPlay'));
const root=path.resolve(__dirname,'..'),uiRoot=path.join(__dirname,'ui');
const resources=app.isPackaged?process.resourcesPath:path.join(root,'resources');
const engineRoot=app.isPackaged?path.join(resources,'app.asar.unpacked'):root;
const validationDir=process.env.WINPLAY_TEST_OUTPUT||path.join(root,'docs/validation');
const native=app.isPackaged?path.join(resources,'native','WinPlay.Platform.exe'):path.join(root,'build/native/WinPlay.Platform.exe');
const runtime=path.join(resources,'node/node.exe'),dataDir=path.join(app.getPath('userData'),'data');
const defaults={language:'system',resolutionMode:'preset',fullScreen:false,closeBehavior:'ask',wirelessMode:'hotspot',lanSsid:'',lanPassword:'',lanChannel:36,lanNetworkInterface:'',lanAccessPointMac:'',width:1280,height:720,fps:60,theme:'system',displayId:0,audioEnabled:true,mediaVolume:1,callVolume:1,inputDevice:'',outputDevice:'',ssid:'',password:'',channel:0,targetBluetooth:'',lastBluetooth:'',networkInterface:''};
let systemMedia,tray,updates,startController,nativeMonitorRead,nativeMonitors=[],updatePromptOpen=false,videoHidden=false;
let videoClosePromptOpen=false,closePromptOpen=false,connectionEpoch=0,reconnecting=false;
let settings={...defaults},main,video,engine,lastConfig,pendingFrames=[],videoReady=false,videoSized=false,videoDecoded=false,pendingVideoSettings,videoPixelSize,videoDisplayId,videoSizingTimer,running=false,closing=false;let diagnostics=[],stats={requested:60,attempt:60,receivedFps:0,decodedFps:0};
function t(text){return I18n.translate(text,settings.language,app.getLocale())}
function dialogText(options){const o={...options};for(const key of ['title','message','detail','checkboxLabel'])if(typeof o[key]==='string')o[key]=t(o[key]);if(o.buttons)o.buttons=o.buttons.map(t);return o}
async function promptUpdate(){if(selfTest||closing||!main||main.isDestroyed()||updatePromptOpen||!updates?.shouldNotify())return;updatePromptOpen=true;updates.markNotified();try{const r=updates.state().release,download=r.installer||r.page,choice=await dialog.showMessageBox(main,dialogText({type:'info',title:'发现新版本',message:t('发现新版：'+r.version),buttons:[r.installer?'下载更新':'查看发行说明','稍后'],defaultId:1,cancelId:1,noLink:true}));if(choice.response===0&&!closing)await shell.openExternal(download)}finally{updatePromptOpen=false}}
function save(){fs.mkdirSync(dataDir,{recursive:true});const file=path.join(dataDir,'settings.dpapi');fs.writeFileSync(file+'.new',safeStorage.encryptString(JSON.stringify(settings)));fs.renameSync(file+'.new',file)}
function load(){try{diagnostics=redactDiagnostics(JSON.parse(fs.readFileSync(path.join(dataDir,'diagnostics.json'),'utf8'))).slice(-150)}catch{}try{const saved=JSON.parse(safeStorage.decryptString(fs.readFileSync(path.join(dataDir,'settings.dpapi'))));settings={...defaults};for(const key of Object.keys(defaults))if(typeof saved[key]===typeof defaults[key])settings[key]=saved[key];save()}catch{}}
function send(type,payload={}){if(type==='now-playing')systemMedia?.update(payload.state,payload.artChanged);else if(type==='position')systemMedia?.position(payload.positionMs);else if(type==='stopped')systemMedia?.clear();if(main&&!main.isDestroyed())main.webContents.send('event',{type,...payload})}
function log(status,detail=''){diagnostics.push({time:new Date().toISOString(),status:redactText(status)||'应用状态',detail:redactText(detail)||''});diagnostics=diagnostics.slice(-150);try{fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(path.join(dataDir,'diagnostics.json'),JSON.stringify(diagnostics))}catch{}send(status.startsWith('网络发现：')||['控制请求','流协商','控制命令','事件通道已连接','建立iAP网络链路','iAP网络数据通道已连接','视频接收端口已就绪','视频TCP通道已连接','音频运行统计','视频运行统计','网络接收端已就绪','网络控制连接已到达'].includes(status)?'diagnostic':'status',{status,detail})}
function restoreMain(){if(!main||main.isDestroyed())return;main.setSkipTaskbar(false);main.restore();main.show();main.focus()}
function hideMain(){if(!main||main.isDestroyed())return;main.setSkipTaskbar(true);main.hide()}
function hideVideo(){if(!video||video.isDestroyed())return;videoHidden=true;video.setSkipTaskbar(true);video.hide()}
function minimizeVideo(){if(!video||video.isDestroyed())return;videoHidden=true;video.setSkipTaskbar(false);video.minimize()}
function restoreVideo(){if(!video||video.isDestroyed()||!videoSized||!videoDecoded)return;videoHidden=false;video.setSkipTaskbar(false);video.restore();video.show();video.focus()}
function updateTray(){tray?.setContextMenu(Menu.buildFromTemplate([{label:t('显示WinPlay'),click:restoreMain},{label:t('显示CarPlay'),enabled:!!video&&!video.isDestroyed(),click:restoreVideo},{type:'separator'},{label:t(running?'停止接收':'启动接收'),click:()=>{if(running){stop();log('接收已停止')}else if(!authExists())log('缺少认证文件','请先在关于页导入认证文件');else start().catch(e=>log('启动接收失败',e.message))}},{type:'separator'},{label:t('退出WinPlay'),click:()=>app.quit()}]))}
function createTray(){tray=new Tray(path.join(resources,'icons','winplay.ico'));tray.setToolTip('WinPlay');tray.on('click',restoreMain);tray.on('double-click',restoreMain);updateTray()}
function createMain(){main=new BrowserWindow({width:900,height:650,minWidth:900,minHeight:560,show:!selfTest,backgroundColor:nativeTheme.shouldUseDarkColors?'#171717':'#ffffff',title:'WinPlay',autoHideMenuBar:true,icon:path.join(resources,'icons','winplay-256.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});main.loadFile(path.join(uiRoot,'index.html'));main.on('close',async event=>{if(closing)return;event.preventDefault();if(closePromptOpen)return;closePromptOpen=true;try{const choice=await chooseCloseBehavior(settings.closeBehavior,()=>dialog.showMessageBox(main,dialogText({type:'question',title:'关闭WinPlay',message:'关闭主窗口时要执行什么操作？',detail:'最小化到托盘会保持CarPlay连接；退出会停止接收。',buttons:['退出WinPlay','最小化到托盘','取消'],defaultId:1,cancelId:2,checkboxLabel:'不再提示',checkboxChecked:false,noLink:true})));if(choice.remember){settings.closeBehavior=choice.remember;save();send('close-behavior',{value:choice.remember})}if(choice.action==='minimize')hideMain();else if(choice.action==='exit')app.quit()}finally{closePromptOpen=false}});main.webContents.setWindowOpenHandler(()=>({action:'deny'}));main.webContents.on('will-navigate',e=>e.preventDefault())}
function selectedDisplay(config=settings){return screen.getAllDisplays().find(d=>d.id===config.displayId)||screen.getPrimaryDisplay()}
function refreshNativeMonitors(){if(nativeMonitorRead)return nativeMonitorRead;nativeMonitorRead=new Promise((resolve,reject)=>execFile(native,['monitors'],{windowsHide:true,timeout:5000},(error,out,err)=>{if(error){nativeMonitors=[];reject(Error(err||'Windows显示器枚举失败'));return}try{const result=JSON.parse(out);if(!Array.isArray(result.items)||!result.items.length||result.items.some(item=>!['x','y','width','height'].every(key=>Number.isInteger(item[key]))||item.width<=0||item.height<=0))throw Error('无法读取显示器物理像素');nativeMonitors=result.items;resolve()}catch(e){nativeMonitors=[];reject(e)}})).finally(()=>{nativeMonitorRead=undefined});return nativeMonitorRead}
function displayPixels(display){if(!nativeMonitors.length)throw Error('无法读取显示器物理像素');return physicalDisplay(display,rect=>screen.dipToScreenRect(null,rect),nativeMonitors)}
function setVideoPixels(){if(!video||video.isDestroyed()||!videoPixelSize)return;const current=video;current.setResizable(true);const handle=current.getNativeWindowHandle().readBigUInt64LE().toString();execFile(native,['window-pixels',handle,String(videoPixelSize.width),String(videoPixelSize.height)],{windowsHide:true,timeout:5000},(error,out)=>{if(video!==current||current.isDestroyed())return;if(error){log('画面窗口尺寸设置失败',error.message);stop();return}try{const actual=JSON.parse(out);if(actual.clientWidth!==videoPixelSize.width||actual.clientHeight!==videoPixelSize.height)throw Error('物理像素尺寸不一致');current.setResizable(false);current.webContents.send('event',{type:'video-viewport',width:videoPixelSize.width,height:videoPixelSize.height});videoSized=true;if(!selfTest&&videoDecoded&&!videoHidden){current.show();current.focus()}}catch(e){log('画面窗口尺寸设置失败',e.message);stop()}})}
function createVideo(config=pendingVideoSettings||settings){if(video&&!video.isDestroyed())return;const target=selectedDisplay(config),size=videoSize(config,displayPixels(target)),bounds=dipVideoBounds(target,size);videoPixelSize=size;videoDisplayId=target.id;videoReady=false;videoSized=false;videoDecoded=false;videoHidden=false;
 video=new BrowserWindow({...bounds,resizable:false,maximizable:false,fullscreenable:false,frame:!size.fullScreen,thickFrame:false,roundedCorners:false,title:'WinPlay · CarPlay',icon:path.join(resources,'icons','winplay-256.png'),show:false,backgroundColor:'#000000',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
 updateTray();video.on('minimize',()=>{videoHidden=true});video.on('restore',()=>{videoHidden=false});video.setMenu(null);video.webContents.setVisualZoomLevelLimits(1,1);video.webContents.on('before-input-event',(event,input)=>{if(input.type==='keyDown'&&input.key==='Escape'){event.preventDefault();minimizeVideo()}if((input.control||input.meta)&&['+','-','=','0'].includes(input.key))event.preventDefault()});video.on('will-resize',event=>event.preventDefault());setVideoPixels();
 video.on('close',async event=>{if(closing||!(running||reconnecting))return;event.preventDefault();if(videoClosePromptOpen)return;videoClosePromptOpen=true;const current=video,epoch=connectionEpoch;try{const choice=await dialog.showMessageBox(current,dialogText({type:'question',title:'断开CarPlay',message:'您确定要断开与iPhone的连接吗？',detail:'断开后将关闭CarPlay画面，并停止接收。',buttons:['断开连接','取消'],defaultId:1,cancelId:1,noLink:true}));if(choice.response===0&&video===current&&!current.isDestroyed()&&connectionEpoch===epoch)stop()}catch(e){if(video===current&&!current.isDestroyed())log('断开确认无法显示',e.message)}finally{videoClosePromptOpen=false}});
 video.loadFile(path.join(uiRoot,'video.html'));video.on('closed',()=>{video=undefined;videoReady=false;videoSized=false;videoDecoded=false;updateTray();if((running||reconnecting)&&!closing)stop()});video.webContents.setWindowOpenHandler(()=>({action:'deny'}));video.webContents.on('will-navigate',e=>e.preventDefault());
 video.webContents.on('did-finish-load',()=>{videoReady=true;video.webContents.setZoomFactor(1);video.webContents.send('event',{type:'video-viewport',width:videoPixelSize.width,height:videoPixelSize.height,fullScreen:videoPixelSize.fullScreen});if(lastConfig)video.webContents.send('event',lastConfig);for(const frame of pendingFrames)video.webContents.send('event',frame);pendingFrames=[]})
}
function closeVideo(){videoReady=false;videoDecoded=false;pendingFrames=[];lastConfig=undefined;if(video&&!video.isDestroyed()){const win=video;video=undefined;win.destroy()}updateTray()}
function worker(){return fork(path.join(engineRoot,'build/engine/run.js'),[],{execPath:runtime,execArgv:[],windowsHide:true,stdio:['ignore','ignore','ignore','ipc'],serialization:'advanced',env:{...process.env,WINPLAY_DATA:dataDir,WINPLAY_NATIVE:native,WINPLAY_RESOURCES:resources}})}
function command(message){if(engine?.connected)engine.send(message)}
function stopped(){running=false;pendingVideoSettings=undefined;updateTray();closeVideo();stats={...stats,receivedFps:0,decodedFps:0,decodedWidth:0,decodedHeight:0};send('stopped');send('metrics',stats)}
function stop(){connectionEpoch++;startController?.abort();startController=undefined;reconnecting=false;if(engine){const previous=engine;engine=undefined;if(previous.connected)previous.send({command:'stop'});setTimeout(()=>previous.kill(),1500).unref()}stopped()}
function handleEngineMessage(msg){
 if(msg.type==='status')log(msg.status,msg.detail)
 else if(msg.type==='video-config'){if(lastConfig?.generation!==msg.generation)pendingFrames=[];lastConfig=msg;if(videoReady)video.webContents.send('event',msg)}
 else if(msg.type==='video-frame'){if(!running){command({command:'video-ack',frameId:msg.frameId,generation:msg.generation});return}try{createVideo()}catch(e){log('画面窗口尺寸设置失败',e.message);stop();return}if(msg.reset)pendingFrames=[];if(videoReady)video.webContents.send('event',msg);else if(pendingFrames.length<16)pendingFrames.push(msg);else{pendingFrames=[];command({command:'video-recover',reason:'ipc-overflow'})}}
 else if(msg.type==='video-diagnostic'){const values={};for(const key of ['receivedFrames','receivedBytes','sentFrames','droppedFrames','backpressurePauses','recoveries','maxInFlight','maxInFlightBytes','inFlight','inFlightBytes','decoderQueueSize'])if(Number.isFinite(msg[key]))values[key]=msg[key];for(const key of ['waitingKeyframe','paused'])if(typeof msg[key]==='boolean')values[key]=msg[key];log('视频运行统计',JSON.stringify(values))}
 else if(msg.type==='connected'){settings.lastBluetooth=engine?.selectedPhone||settings.targetBluetooth||settings.lastBluetooth;save();send(msg.type,msg)}
 else if(msg.type==='metrics'){stats={...stats,...msg};send('metrics',stats)}
 else if(msg.type==='stopped'){stopped()}
 else if(msg.type==='show-settings')restoreMain()
 else send(msg.type,msg)
}
async function start(config={...settings}){
 if(running)return;
 const target=selectedDisplay(config),size=videoSize(config,displayPixels(target));
 let resolved={...resolveConnectionSettings(config),width:size.width,height:size.height};
 if(!resolved.targetBluetooth)resolved.targetBluetooth=settings.lastBluetooth;
 validateSettings(resolved,{network:resolved.wirelessMode!=='hotspot'});
 const ticket=++connectionEpoch;running=true;send('starting');updateTray();
 try{
  pendingVideoSettings={...config};const controller=new AbortController();startController=controller;
  let lastNetworkWait='';
  const networkDetail=result=>result.diagnostic?(typeof result.diagnostic==='string'?result.diagnostic:JSON.stringify(result.diagnostic)):result.code||'NETWORK_NOT_READY';
  const network=await require('./network-selection.cjs').waitForNetwork(resolved.wirelessMode,resolved.networkInterface,{signal:controller.signal,onWait:result=>{
   const detail=networkDetail(result);
   if(!lastNetworkWait)log('正在等待网络接口就绪');
   if(detail!==lastNetworkWait){lastNetworkWait=detail;log('网络发现：热点接口检查',detail)}
  }});
  if(connectionEpoch!==ticket||!running)return;
  if(resolved.wirelessMode==='hotspot'&&network.diagnostic&&networkDetail(network)!==lastNetworkWait)log('网络发现：热点接口检查',networkDetail(network));
  if(!network.ok)throw Error(network.error);
  resolved.networkInterface=network.name;
  if(resolved.wirelessMode==='hotspot'){
   const current=await readCurrentNetwork('hotspot',{snapshot:network,includePassword:true});
   if(connectionEpoch!==ticket||!running)return;
   if(current.hotspotState==='Off')throw Error('Windows移动热点未开启，请开启热点后重试');
   if(current.hotspotState==='InTransition')throw Error('Windows移动热点正在启动，请等待共享接口就绪');
   if(current.ok){
    const sameNetwork=current.ssid===resolved.ssid;
    resolved={...resolved,ssid:current.ssid,password:current.passwordRead&&typeof current.password==='string'?current.password:sameNetwork?resolved.password:'',...(Number.isInteger(current.channel)?{channel:current.channel}:{})};
   }
   log('网络发现：热点参数检查',current.ok?'已读取Windows移动热点配置':'未能读取Windows移动热点配置，使用手动配置');
   validateSettings(resolved);
  }else if(resolved.wirelessMode==='lan'&&network.item?.wireless){
   const current=await readCurrentNetwork('lan',{interfaceName:network.name,includePassword:true});
   if(connectionEpoch!==ticket||!running)return;
   if(current.ok&&current.interfaceName?.toLowerCase()===network.name.toLowerCase()&&current.ssid!==resolved.ssid)throw Error('当前Wi-Fi与配置不一致，请读取当前网络并重新确认共享密码');
   resolved=refreshLanParameters(resolved,current);
   if(current.ok&&current.ssid===resolved.ssid&&current.interfaceName?.toLowerCase()===network.name.toLowerCase()&&current.passwordRead&&typeof current.password==='string')resolved.password=current.password;
   log('网络发现：局域网参数检查',current.ok?'已读取所选Wi-Fi接口':'未能读取当前Wi-Fi，使用手动配置');
  }
  startController=undefined;const proc=worker();engine=proc;proc.selectedPhone=resolved.targetBluetooth;
  proc.on('message',msg=>{if(engine===proc)handleEngineMessage(msg)});
  proc.on('exit',code=>{if(engine!==proc)return;engine=undefined;if(running)log('接收已结束',code&&code!==0?'接收进程退出，请查看关于页日志':'');stopped()});
  proc.on('error',()=>{if(engine!==proc)return;log('接收进程无法启动');stop()});
  proc.send({command:'start',settings:resolved});
 }catch(e){if(connectionEpoch!==ticket)return;startController=undefined;log('启动接收失败',e.message);stopped();throw e}
}
function validateSettings(s,{network=true}={}){if(![30,60,90,120].includes(s.fps))throw new Error('帧率必须为30、60、90或120');if(!Number.isInteger(s.width)||!Number.isInteger(s.height)||s.width<320||s.height<200||s.width%2||s.height%2)throw new Error('请填写不超过所选屏幕物理分辨率的偶数像素尺寸');if(s.wirelessMode==='lan'&&s.accessPointMac&&!/^[\da-f]{2}(:[\da-f]{2}){5}$/i.test(s.accessPointMac.trim()))throw new Error('接入点BSSID格式无效');if(network&&(!s.ssid.trim()||Buffer.byteLength(s.ssid)>32||s.ssid.includes('\0')))throw new Error('请填写当前无线模式的实际Wi-Fi名称，最多32字节');if(network&&(s.password.length<8||s.password.length>63||s.password.includes('\0')))throw new Error('Wi-Fi共享密码必须为8—63位；本版不支持企业或网页登录凭据');if(!/^[\da-f]{2}(:[\da-f]{2}){5}$/i.test(s.targetBluetooth))throw new Error('请选择已配对的iPhone');if(network&&(!Number.isInteger(s.channel)||s.channel<(s.wirelessMode==='hotspot'?0:1)||s.channel>196))throw new Error(s.wirelessMode==='hotspot'?'热点信道必须为0—196，0表示自动':'Wi-Fi信道必须为1—196')}
function checkSender(event){const windows=[main,video].filter(Boolean);if(!windows.some(w=>!w.isDestroyed()&&w.webContents.id===event.sender.id))throw new Error('IPC来源无效')}
function authExists(){return ['identity.pk8.dpapi','certificate.p7b.dpapi'].every(n=>fs.existsSync(path.join(dataDir,'authentication',n)))||['identity.pk8','certificate.p7b'].every(n=>fs.existsSync(path.join(resources,'authentication',n)))}
ipcMain.handle('call',async(event,op,arg)=>{checkSender(event);try{switch(op){
 case 'state':return {ok:true,settings,version:app.getVersion(),locale:app.getLocale(),architecture:process.arch,updates:updates?.state(),running,dark:nativeTheme.shouldUseDarkColors,auth:authExists(),stats,diagnostics};
 case 'save':{if(Object.hasOwn(arg,'closeBehavior'))validateCloseBehavior(arg.closeBehavior);const allowed=Object.keys(defaults);const next={...settings};for(const key of allowed)if(Object.hasOwn(arg,key)&&typeof arg[key]===typeof defaults[key])next[key]=arg[key];if(!['system','zh-Hans','zh-Hant','en'].includes(next.language))throw Error('语言无效');if(!['system','light','dark'].includes(next.theme))throw new Error('主题无效');next.mediaVolume=Math.max(0,Math.min(1,next.mediaVolume));next.callVolume=Math.max(0,Math.min(1,next.callVolume));if(!['hotspot','lan'].includes(next.wirelessMode))throw new Error('无线模式无效');videoSize(next,displayPixels(screen.getAllDisplays().find(d=>d.id===next.displayId)||screen.getPrimaryDisplay()));const languageChanged=next.language!==settings.language;settings=next;save();if(languageChanged){updateTray();send('language',{language:settings.language,locale:app.getLocale()})}nativeTheme.themeSource=settings.theme;send('appearance',{dark:nativeTheme.shouldUseDarkColors});command({command:'audio',mediaVolume:settings.mediaVolume,callVolume:settings.callVolume});send('audio-enabled',{enabled:settings.audioEnabled});if(!running)send('audio-devices',{inputDevice:settings.inputDevice,outputDevice:settings.outputDevice});return {ok:true};}
 case 'start':if(!authExists())throw new Error('请先在关于页导入有使用权限的配套认证材料');await start();return {ok:true};
 case 'restart':{if(!authExists())throw Error('请先导入认证文件');const target=selectedDisplay(),size=videoSize(settings,displayPixels(target));validateSettings({...resolveConnectionSettings(settings),width:size.width,height:size.height,targetBluetooth:settings.targetBluetooth||settings.lastBluetooth},{network:settings.wirelessMode!=='hotspot'});const snapshot={...settings},previous=engine;stop();const ticket=connectionEpoch;reconnecting=true;if(previous)await new Promise(resolve=>{const timer=setTimeout(()=>{previous.kill();resolve()},2200);previous.once('exit',()=>{clearTimeout(timer);resolve()})});if(connectionEpoch!==ticket)return {ok:false,error:'重新连接已取消'};reconnecting=false;await start(snapshot);return {ok:true};}
 case 'show-video':if(!video||video.isDestroyed())throw Error('画面窗口尚未创建');if(!videoSized||!videoDecoded)throw Error('正在准备画面窗口');restoreVideo();return {ok:true};
 case 'open-auth':{const dir=path.join(dataDir,'authentication');fs.mkdirSync(dir,{recursive:true});const error=await shell.openPath(dir);if(error)throw Error(error);return {ok:true};}
 case 'open-log':{const file=path.join(dataDir,'diagnostics.json');fs.writeFileSync(file,JSON.stringify(redactDiagnostics(diagnostics)));const error=await shell.openPath(file);if(error)throw Error(error);return {ok:true};}
 case 'settings-location':await shell.openExternal('ms-settings:privacy-location');return {ok:true};
 case 'read-current-network':return await readCurrentNetwork(arg?.mode,{interfaceName:arg?.mode==='lan'?settings.lanNetworkInterface:undefined,includePassword:true});
 case 'check-updates':await updates.check();if(updates.state().status==='发现新版本')promptUpdate().catch(()=>{});return {ok:true,updates:updates.state()};
 case 'set-automatic-updates':if(typeof arg?.enabled!=='boolean')throw Error('更新选项无效');updates.setAutomatic(arg.enabled).then(value=>{if(arg.enabled&&value.automatic&&value.status==='发现新版本')promptUpdate().catch(()=>{})}).catch(()=>{});return {ok:true,updates:updates.state()};
 case 'open-release':await shell.openExternal(updates.releaseUrl());return {ok:true};
 case 'download-update':{const url=updates.state().release?.installer;if(!url)throw Error('暂无适合当前架构的安装包，请查看发行说明');await shell.openExternal(url);return {ok:true};}
 case 'open-project':await shell.openExternal('https://github.com/Roylyl/WinPlay');return {ok:true};
 case 'stop':stop();log('接收已停止');return {ok:true};
 case 'displays':await refreshNativeMonitors();return {ok:true,items:screen.getAllDisplays().map(d=>{const p=displayPixels(d);return {id:d.id,label:d.label||`显示器${d.id}`,width:p.width,height:p.height,scaleFactor:d.scaleFactor,internal:d.internal,refreshRate:d.displayFrequency,primary:d.id===screen.getPrimaryDisplay().id}})};
 case 'networks':return await require('./network-selection.cjs').listNetworks();
 case 'bluetooth':return await new Promise(resolve=>execFile(native,['list'],{windowsHide:true,timeout:15000},(error,out,err)=>{if(error)return resolve({ok:false,error:err||'蓝牙设备枚举失败'});try{resolve({ok:true,...JSON.parse(out)})}catch{resolve({ok:false,error:'蓝牙枚举响应无效'})}}));
 case 'settings-hotspot':await shell.openExternal('ms-settings:network-mobilehotspot');return {ok:true};
 case 'settings-bluetooth':await shell.openExternal('ms-settings:bluetooth');return {ok:true};
 case 'import-auth':{if(running)throw new Error('请先停止接收再导入认证材料');const selection=await dialog.showOpenDialog(main,{title:t('选择identity.pk8与certificate.p7b'),filters:[{name:t('认证文件'),extensions:['pk8','p7b']}],properties:['openFile','multiSelections']});if(selection.canceled)return {ok:false,error:'已取消导入'};const keys=selection.filePaths.filter(file=>path.extname(file).toLowerCase()==='.pk8'),certs=selection.filePaths.filter(file=>path.extname(file).toLowerCase()==='.p7b');if(keys.length!==1||certs.length!==1)throw Error('请选择一个identity.pk8和一个certificate.p7b');const key={filePaths:keys},cert={filePaths:certs};const keyBytes=fs.readFileSync(key.filePaths[0]),certBytes=fs.readFileSync(cert.filePaths[0]);if(keyBytes.length>16384||certBytes.length>1024*1024)throw new Error('认证文件大小不合理');return await new Promise(resolve=>{const p=worker();const timer=setTimeout(()=>{p.kill();resolve({ok:false,error:'认证导入超时'})},15000);p.on('message',m=>{if(m.type==='auth-imported'){clearTimeout(timer);resolve({ok:true})}if(m.type==='status'){clearTimeout(timer);resolve({ok:false,error:m.status})}});p.on('error',()=>{clearTimeout(timer);resolve({ok:false,error:'认证导入进程无法启动'})});p.send({command:'import-auth',key:keyBytes,cert:certBytes})});}
 case 'export-diagnostics':{const destination=await dialog.showSaveDialog(main,{title:t('导出日志'),defaultPath:'WinPlay-'+app.getVersion()+'-diagnostics.json',filters:[{name:'JSON',extensions:['json']}]});if(destination.canceled)return {ok:false,error:'已取消导出'};fs.writeFileSync(destination.filePath,JSON.stringify({version:app.getVersion(),platform:process.platform,metrics:stats,authenticationImported:authExists(),messages:redactDiagnostics(diagnostics)},null,2));return {ok:true};}
 default:throw new Error('未知操作');}}catch(e){return {ok:false,error:e.message}}});
const testInputs=[];
ipcMain.on('input',(event,msg)=>{checkSender(event);if(selfTest&&msg.command==='touch')testInputs.push(msg);const allowed=['touch','media','seek','mic','video-ack','video-recover','request-keyframe'];if(allowed.includes(msg.command))command(msg);if(msg.command==='decoded'){stats.decodedFps=msg.fps;stats.decodedWidth=msg.width;stats.decodedHeight=msg.height;send('metrics',stats)}if(msg.command==='video-visible'&&video&&!video.isDestroyed()){videoDecoded=true;if((!selfTest||windowSelfTest)&&videoSized&&!videoHidden){video.show();video.focus()}}if(msg.command==='video-minimize'&&video&&!video.isDestroyed())minimizeVideo();if(msg.command==='video-close'&&video&&!video.isDestroyed())video.close();if(msg.command==='video-recovery')log('视频解码恢复',String(msg.reason).slice(0,200));if(msg.command==='decode-error'){log('视频解码失败',msg.reason);stop()}if(msg.command==='audio-diagnostic')log('音频运行统计',String(msg.reason).slice(0,800));if(msg.command==='audio-error')log('音频处理需要检查',String(msg.reason).slice(0,200))});
app.on('before-quit',()=>{closing=true;systemMedia?.close();tray?.destroy();tray=undefined;stop()});
app.whenReady().then(async()=>{fs.mkdirSync(dataDir,{recursive:true});load();await refreshNativeMonitors().catch(error=>log('显示器物理尺寸查询失败',error.message));if(windowSelfTest){runWindowSelfTest().catch(error=>{fs.mkdirSync(validationDir,{recursive:true});fs.writeFileSync(path.join(validationDir,'window-failure.txt'),error.stack);closing=true;app.exit(1)});return}if(selfTest)settings.language='zh-Hans';updates=new Updates({version:app.getVersion(),dataDir,onChange:value=>send('updates',{updates:value})});nativeTheme.themeSource=settings.theme;session.defaultSession.setPermissionRequestHandler((wc,permission,cb)=>cb(wc.id===main?.webContents.id&&permission==='media'));session.defaultSession.setPermissionCheckHandler((wc,permission)=>wc?.id===main?.webContents.id&&permission==='media');nativeTheme.on('updated',()=>send('appearance',{dark:nativeTheme.shouldUseDarkColors}));screen.on('display-metrics-changed',()=>{clearTimeout(videoSizingTimer);videoSizingTimer=setTimeout(async()=>{try{await refreshNativeMonitors();if(!video||video.isDestroyed())return;const target=screen.getAllDisplays().find(d=>d.id===videoDisplayId);if(!target)throw Error('显示器已断开');videoSize({...videoPixelSize,fullScreen:false},displayPixels(target));video.setBounds(dipVideoBounds(target,videoPixelSize));setVideoPixels()}catch(e){log('显示器配置已变化',e.message);stop()}},200)});screen.on('display-removed',()=>{if(video&&!video.isDestroyed()&&!screen.getAllDisplays().some(d=>d.id===videoDisplayId)){log('显示器已断开，请重新选择显示位置');stop()}});createMain();createTray();if(!selfTest)main.webContents.once('did-finish-load',()=>setTimeout(()=>{if(!closing)updates.check({automatic:true}).then(value=>{if(value.automatic&&value.status==='发现新版本')promptUpdate().catch(()=>{})}).catch(()=>{})},5000).unref());systemMedia=new SystemMedia(path.join(app.isPackaged?path.join(resources,'native'):path.join(root,'build/native'),'WinPlay.Media.exe'),m=>{if(['media','seek'].includes(m.command))command(m)},reason=>log('系统媒体同步失败',reason));if(selfTest)main.webContents.once('did-finish-load',()=>runSelfTest().catch(e=>{fs.mkdirSync(validationDir,{recursive:true});fs.writeFileSync(path.join(validationDir,'electron-failure.txt'),e.stack);app.exit(1)}))});
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function runWindowSelfTest(){
 const result={kind:'targeted Windows taskbar minimize check',electron:process.versions.electron,checks:[]};
 const check=(name,passed,detail='')=>{result.checks.push({name,passed,detail});fs.mkdirSync(validationDir,{recursive:true});fs.writeFileSync(path.join(validationDir,'window-smoke.json'),JSON.stringify(result,null,2));if(!passed)throw Error(name+': '+detail)};
 try{
  for(const fullScreen of [true,false]){
   const mode=fullScreen?'native fullscreen':'fixed window';running=true;
   createVideo({...settings,fullScreen,width:960,height:540});
   const current=video;for(let attempt=0;attempt<50&&(!videoReady||!videoSized);attempt++)await delay(100);
   check(mode+' becomes ready',video===current&&videoReady&&videoSized&&videoPixelSize.fullScreen===fullScreen);
   check(mode+' stays hidden before a decoded frame',!current.isVisible()&&!videoDecoded);
   restoreVideo();check(mode+' cannot restore before a decoded frame',!current.isVisible());
   await current.webContents.executeJavaScript("winplay.input({command:'video-visible'})");await delay(100);
   check(mode+' displays after the first decoded frame',current.isVisible()&&videoDecoded);
   const skipRequests=[],setSkipTaskbar=current.setSkipTaskbar.bind(current);
   current.setSkipTaskbar=value=>{skipRequests.push(value);setSkipTaskbar(value)};
   const hiddenBeforeMinimize=[],minimize=current.minimize.bind(current);current.minimize=()=>{hiddenBeforeMinimize.push(videoHidden);minimize()};
   current.show();current.focus();await delay(100);
   current.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});await delay(150);
   check(mode+' Escape minimizes and retains the session',current.isMinimized()&&!current.isDestroyed()&&video===current&&running&&videoHidden&&!videoClosePromptOpen,JSON.stringify({minimized:current.isMinimized(),visible:current.isVisible(),running,videoHidden,skipRequests}));
   await current.webContents.executeJavaScript("winplay.input({command:'video-visible'})");await delay(100);
   check(mode+' later video visibility does not restore the window',current.isMinimized()&&videoHidden&&running);
   restoreVideo();await delay(100);
   check(mode+' restores from taskbar',!current.isMinimized()&&current.isVisible()&&!videoHidden&&running);
   await current.webContents.executeJavaScript("winplay.input({command:'video-minimize'})");await delay(150);
   check(mode+' renderer minimize IPC retains the window',current.isMinimized()&&!current.isDestroyed()&&videoHidden&&running&&!videoClosePromptOpen);
   check(mode+' keeps taskbar visibility and marks hidden before native minimize',skipRequests.length>=3&&skipRequests.every(value=>value===false)&&hiddenBeforeMinimize.length===2&&hiddenBeforeMinimize.every(value=>value===true));
   running=false;closeVideo();await delay(50);
  }
  result.completed=true;fs.mkdirSync(validationDir,{recursive:true});fs.writeFileSync(path.join(validationDir,'window-smoke.json'),JSON.stringify(result,null,2));
  const failure=path.join(validationDir,'window-failure.txt');if(fs.existsSync(failure))fs.unlinkSync(failure);
 }finally{running=false;closing=true;closeVideo()}
 app.exit(0);
}
async function runSelfTest(){main.showInactive();await delay(700);const dir=validationDir;fs.mkdirSync(dir,{recursive:true});const result={date:'2026-10-02',kind:'synthetic Windows Electron test',electron:process.versions.electron,packaged:app.isPackaged,parentExecArgv:process.execArgv,checks:[]};const check=(name,passed,detail='')=>{result.checks.push({name,passed,detail});fs.writeFileSync(path.join(dir,'electron-smoke.json'),JSON.stringify(result,null,2));if(!passed)throw new Error(name+' failed: '+detail)};
 check('first launch defaults to 60fps; experimental PCM control removed',settings.fps===60&&await main.webContents.executeJavaScript(`document.getElementById('fps').value==='60'&&!document.getElementById('mediaCodec')`));
 const physical=displayPixels(selectedDisplay());check('display request uses current Win32 physical monitor dimensions',nativeMonitors.some(item=>item.width===physical.width&&item.height===physical.height));
 main.show();main.minimize();await delay(150);check('main minimize button keeps normal taskbar window',main.isMinimized());hideMain();check('main minimizes to tray',!!tray&&!main.isVisible());restoreMain();check('tray restores main',main.isVisible());
 await main.webContents.executeJavaScript(`document.getElementById('wirelessMode').value='lan';document.getElementById('wirelessMode').dispatchEvent(new Event('change'))`);await delay(120);check('wireless-only connection UI and settings',await main.webContents.executeJavaScript(`document.getElementById('wirelessMode').options.length===2&&!document.getElementById('wireless-fields').hidden&&document.querySelectorAll('.nav').length===4`));check('LAN mode selects router settings and location action',await main.webContents.executeJavaScript(`!document.getElementById('lan-bssid').hidden&&document.getElementById('hotspot-settings').textContent==='打开定位设置'&&document.getElementById('ssid-label').textContent.includes('局域网')`));await main.webContents.executeJavaScript(`document.getElementById('wirelessMode').value='hotspot';document.getElementById('wirelessMode').dispatchEvent(new Event('change'))`);await delay(120);check('hotspot mode selects local AP settings',await main.webContents.executeJavaScript(`document.getElementById('lan-bssid').hidden&&document.getElementById('hotspot-settings').textContent==='打开移动热点'&&document.getElementById('ssid-label').textContent.includes('热点')`));
 check('four settings pages',await main.webContents.executeJavaScript(`document.querySelectorAll('.page').length===4 && document.querySelectorAll('.nav').length===4`));
 await main.webContents.executeJavaScript(`document.querySelector('[data-page="about"]').click()`);await delay(80);check('About groups version updates and folded private tools without receiver footer',await main.webContents.executeJavaScript(`!document.getElementById('about').hidden&&document.getElementById('receiver-footer').hidden&&!document.getElementById('recent-logs').open&&!document.getElementById('authentication').open&&!!document.getElementById('check-updates')&&document.getElementById('automatic-updates').checked`));
 for(const [language,title] of [['en','About'],['zh-Hant','關於'],['zh-Hans','关于']]){await main.webContents.executeJavaScript(`document.getElementById('language').value=${JSON.stringify(language)};document.getElementById('language').dispatchEvent(new Event('change'))`);await delay(150);check('live application language '+language,await main.webContents.executeJavaScript(`document.querySelector('#about h1').textContent===${JSON.stringify(title)}`))}
 fs.writeFileSync(path.join(dir,'settings-about.png'),(await main.webContents.capturePage()).toPNG());await main.webContents.executeJavaScript(`(async()=>{document.querySelector('[data-page="display"]').click();document.getElementById('resolutionPreset').value='custom';await document.getElementById('resolutionPreset').onchange();document.getElementById('width').value='960';document.getElementById('width').dispatchEvent(new Event('input'));document.getElementById('height').value='540';document.getElementById('height').dispatchEvent(new Event('input'))})()`);check('custom resolution preview changes without applying reception',await main.webContents.executeJavaScript(`!document.getElementById('custom-size').hidden&&document.getElementById('request-pixels').textContent==='960×540'`));fs.writeFileSync(path.join(dir,'settings-display.png'),(await main.webContents.capturePage()).toPNG());await main.webContents.executeJavaScript(`(async()=>{document.getElementById('resolutionPreset').value='1280x720';await document.getElementById('resolutionPreset').onchange();document.querySelector('[data-page="connection"]').click()})()`);
 const themeColors=[];for(const dark of [false,true]){await main.webContents.executeJavaScript(`document.body.classList.toggle('dark',${dark})`);await delay(200);themeColors.push(await main.webContents.executeJavaScript(`getComputedStyle(document.body).backgroundColor`));fs.writeFileSync(path.join(dir,`settings-${dark?'dark':'light'}.png`),(await main.webContents.capturePage()).toPNG())}check('light and dark settings appearances differ',themeColors[0]!==themeColors[1],JSON.stringify(themeColors));
 await main.webContents.executeJavaScript(`(async()=>{document.querySelector('[data-page="display"]').click();document.getElementById('resolutionPreset').value='custom';await document.getElementById('resolutionPreset').onchange();document.getElementById('width').value=String(Number(document.getElementById('width').max)+2);await document.getElementById('width').onchange();await document.getElementById('start').onclick()})()`);check('invalid custom resolution keeps draft and blocks reception',!running&&!video&&await main.webContents.executeJavaScript(`Number(document.getElementById('width').value)>Number(document.getElementById('width').max)&&!document.getElementById('display-error').hidden`));await main.webContents.executeJavaScript(`(async()=>{document.getElementById('resolutionPreset').value='1280x720';await document.getElementById('resolutionPreset').onchange();document.getElementById('toast').hidden=true;document.querySelector('[data-page="connection"]').click()})()`);check('valid resolution clears the draft error',await main.webContents.executeJavaScript(`document.getElementById('display-error').hidden`));
 main.setSize(820,700);await delay(150);check('narrow layout does not horizontally overflow',await main.webContents.executeJavaScript(`document.documentElement.scrollWidth<=window.innerWidth`));fs.writeFileSync(path.join(dir,'settings-narrow.png'),(await main.webContents.capturePage()).toPNG());main.setSize(1050,780);
 const fixture=await main.webContents.executeJavaScript(`(async()=>{const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=720;const c=canvas.getContext('2d');const colors=['#fafafa','#c8ed71','#56d5b4','#4099dc','#925dd5','#e26782'];colors.forEach((color,i)=>{c.fillStyle=color;c.fillRect(i*canvas.width/6,0,canvas.width/6,canvas.height)});c.fillStyle='#171717';c.fillRect(80,230,790,220);c.fillStyle='#fff';c.font='bold 58px Segoe UI';c.fillText(${JSON.stringify('WinPlay'+app.getVersion())},120,320);c.font='26px Segoe UI';c.fillText('Synthetic encrypted video · 1280 × 720',120,375);const frames=[];let config;const encoder=new VideoEncoder({output(chunk,meta){const b=new Uint8Array(chunk.byteLength);chunk.copyTo(b);frames.push(b);if(meta.decoderConfig?.description)config=new Uint8Array(meta.decoderConfig.description)},error(e){throw e}});encoder.configure({codec:'avc1.42001f',width:1280,height:720,bitrate:2000000,framerate:30,avc:{format:'avc'},hardwareAcceleration:'prefer-software'});for(let i=0;i<5;i++){const frame=new VideoFrame(canvas,{timestamp:i*33333});encoder.encode(frame,{keyFrame:true});frame.close()}await encoder.flush();encoder.close();return {config,frames}})()`);
 check('H264 encoder fixture generated',fixture.config?.length>0&&fixture.frames.length===5);
 running=true;send('starting');engine=fork(path.join(engineRoot,'build/engine/selfTest.js'),[],{execPath:runtime,execArgv:[],windowsHide:true,stdio:['ignore','ignore','pipe','ipc'],serialization:'advanced'});engine.stderr.on('data',b=>{result.workerError=String(b).slice(-2000)});engine.on('message',handleEngineMessage);engine.send({command:'fixture',...fixture});for(let i=0;i<40&&(!video||!stats.decodedFps);i++)await delay(200);
 check('encrypted TCP video decoded into dedicated window',!!video&&stats.decodedWidth===1280&&stats.decodedHeight===720&&stats.decodedFps>0,JSON.stringify(stats));video.show();video.minimize();await delay(150);check('CarPlay minimize button keeps taskbar window and connection',video.isMinimized()&&running);restoreVideo();hideVideo();check('CarPlay hides to tray',!video.isVisible()&&running);restoreVideo();check('tray restores CarPlay',video.isVisible());video.showInactive();await delay(150);fs.writeFileSync(path.join(dir,'synthetic-video.png'),(await video.webContents.capturePage()).toPNG());
 const resizedFixture=await main.webContents.executeJavaScript(`(async()=>{const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;const c=canvas.getContext('2d');const colors=['#fafafa','#c8ed71','#56d5b4','#4099dc','#925dd5','#e26782'];colors.forEach((color,i)=>{c.fillStyle=color;c.fillRect(i*canvas.width/6,0,canvas.width/6,canvas.height)});c.fillStyle='#171717';c.fillRect(80,230,790,220);c.fillStyle='#fff';c.font='bold 58px Segoe UI';c.fillText(${JSON.stringify('WinPlay'+app.getVersion())},120,320);c.font='26px Segoe UI';c.fillText('Synthetic encrypted video · 960 × 540',120,375);const frames=[];let config;const encoder=new VideoEncoder({output(chunk,meta){const b=new Uint8Array(chunk.byteLength);chunk.copyTo(b);frames.push(b);if(meta.decoderConfig?.description)config=new Uint8Array(meta.decoderConfig.description)},error(e){throw e}});encoder.configure({codec:'avc1.42001f',width:960,height:540,bitrate:2000000,framerate:30,avc:{format:'avc'},hardwareAcceleration:'prefer-software'});for(let i=0;i<5;i++){const frame=new VideoFrame(canvas,{timestamp:i*33333});encoder.encode(frame,{keyFrame:true});frame.close()}await encoder.flush();encoder.close();return {config,frames}})()`);
 engine.send({command:'reconfigure',...resizedFixture});for(let i=0;i<30&&stats.decodedWidth!==960;i++)await delay(200);check('smart scaling resolution change resumes decoded video',stats.decodedWidth===960&&stats.decodedHeight===540,JSON.stringify(stats));engine.send({command:'reconfigure',...fixture});for(let i=0;i<30&&stats.decodedWidth!==1280;i++)await delay(200);check('resolution switches back without reconnecting',stats.decodedWidth===1280&&stats.decodedHeight===720);
 const originalDialog=dialog.showMessageBox;let promptCount=0;try{dialog.showMessageBox=async(_parent,options)=>{promptCount++;check('CarPlay close asks to disconnect',options.message==='您确定要断开与iPhone的连接吗？'&&options.cancelId===1);return {response:1}};video.close();await delay(100);check('cancel close keeps video and reception',!!video&&running);dialog.showMessageBox=originalDialog}finally{dialog.showMessageBox=originalDialog}
 video.webContents.sendInputEvent({type:'mouseDown',x:350,y:300,button:'left',clickCount:1});video.webContents.sendInputEvent({type:'mouseMove',x:420,y:330,button:'left'});video.webContents.sendInputEvent({type:'mouseUp',x:420,y:330,button:'left',clickCount:1});video.webContents.sendInputEvent({type:'mouseWheel',x:500,y:350,deltaY:90,deltaX:0,canScroll:true});await delay(300);
 check('mouse drag and wheel produce bounded HID touch coordinates',testInputs.length>=4&&testInputs.some(t=>t.down)&&testInputs.some(t=>!t.down)&&testInputs.every(t=>t.x>=0&&t.x<=1&&t.y>=0&&t.y<=1),`${testInputs.length} touch events`);
 const mediaApi=await main.webContents.executeJavaScript(`(async()=>{try{return {mediaSession:'mediaSession' in navigator,audioDecoder:typeof AudioDecoder,opusEncoder:(await AudioEncoder.isConfigSupported({codec:'opus',sampleRate:48000,numberOfChannels:1,bitrate:48000})).supported}}catch(e){return {error:e.message}}})()`);check('Windows Chromium media interfaces available',mediaApi.mediaSession&&mediaApi.audioDecoder==='function'&&mediaApi.opusEncoder,JSON.stringify(mediaApi));
 const codecRates=await main.webContents.executeJavaScript(`(async()=>{const result={};for(const sampleRate of [16000,24000,48000]){try{result[sampleRate]=(await AudioEncoder.isConfigSupported({codec:'opus',sampleRate,numberOfChannels:1,bitrate:48000,opus:{frameDuration:20000}})).supported}catch(e){result[sampleRate]=e.message}}return result})()`);check('Opus uplink negotiated sample rates',Object.values(codecRates).every(v=>v===true),JSON.stringify(codecRates));
 send('now-playing',{state:{title:'合成测试曲目',artist:'WinPlay test',album:'Public fixture',trackId:'1',durationMs:120000,positionMs:1000,playing:true,canSeek:true,generation:0,artwork:new Uint8Array([137,80,78,71,13,10,26,10,0])},artChanged:true});await delay(80);
 const coverBefore=await main.webContents.executeJavaScript(`navigator.mediaSession.metadata.artwork[0]?.src`);send('now-playing',{state:{title:'歌名字段中的歌词',artist:'WinPlay test',album:'Public fixture',trackId:'1',durationMs:120000,positionMs:2000,playing:true,canSeek:true,generation:0},artChanged:false});await delay(80);
 check('MediaSession lyrics keep artwork URL and seek state',await main.webContents.executeJavaScript(`navigator.mediaSession.metadata.title==='歌名字段中的歌词'&&navigator.mediaSession.metadata.artwork[0]?.src===${JSON.stringify(coverBefore)}&&!document.getElementById('seek').disabled`));
 await main.webContents.executeJavaScript(`winplayAudio.prepare({inputDevice:'',outputDevice:''})`);send('audio-config',{id:999,opts:{codec:'pcm',clockRate:48000,channels:2,latencyMs:60,realtime:true}});await delay(50);send('audio-active',{id:999,active:true});send('audio-volume',{id:999,level:.5});send('audio',{id:999,sample:0,sequence:1,data:new Uint8Array(3840)});await delay(100);check('Windows audio endpoint stream created',await main.webContents.executeJavaScript(`winplayAudio.outputState().direct&&winplayAudio.outputState().state==='running'&&winplayAudio.outputState().sampleRate===48000`));send('audio-close',{id:999});
 engine.send({command:'stop'});await delay(500);check('passive disconnect closes video and restores start button',!video&&!running&&await main.webContents.executeJavaScript(`document.getElementById('start').textContent==='启动接收'`));
 check('disconnect clears system media metadata',await main.webContents.executeJavaScript(`navigator.mediaSession.metadata===null&&navigator.mediaSession.playbackState==='none'`));
 running=true;send('starting');createVideo();try{dialog.showMessageBox=async()=>({response:0});video.close();await delay(150);check('confirm close stops reception and closes video',!video&&!running&&await main.webContents.executeJavaScript(`document.getElementById('start').textContent==='启动接收'`))}finally{dialog.showMessageBox=originalDialog}
 fs.writeFileSync(path.join(dir,'electron-smoke.json'),JSON.stringify(result,null,2));if(fs.existsSync(path.join(dir,'electron-failure.txt')))fs.unlinkSync(path.join(dir,'electron-failure.txt'));stop();app.exit(0);
}
app.on('window-all-closed',()=>{if(!windowSelfTest)app.quit()});app.on('before-quit',stop);
